// GERADO A PARTIR DO ANEXO I DA PORTARIA GM/MMA Nº 1.667, DE 27 DE
// ABRIL DE 2026, publicada no DOU de 28/04/2026, edição 78, seção 1,
// página 96. São as 490 linhas da Lista, na ordem em que ela as traz.
//
// Nada aqui foi acrescentado. A Lista não traz nome popular: só nome
// científico, família, ordem, classe e grupo taxonômico. Os dois
// caminhos que existem para chegar ao nome popular sem inventar são a
// IN 53, para as 11 espécies que estão nas duas normas, e a coluna
// "Nome comum" da Portaria 445/2014, revogada — ver `pop445` abaixo.
//
// A coluna `marca` guarda o asterisco que a Lista imprime ao lado do
// número de 94 itens. O texto publicado no DOU não traz legenda para
// ele. Está reproduzido como está, sem interpretação.
//
// O campo `pop445` traz o nome comum que a Portaria MMA nº 445/2014
// dava à mesma espécie. Essa portaria foi REVOGADA pela 1.667 e não
// vale mais como norma: o nome está aqui só para achar a espécie na
// busca, porque a norma em vigor não traz nome popular nenhum. Sai
// direto da coluna "Nome comum" da 445; onde ela dizia "Desconhecido",
// o campo fica vazio.

/// Grupo taxonômico, como a Lista o nomeia.
const gruposAmeacadas = <String>[
  'Peixes Continentais',
  'Peixes Marinhos (ósseos)',
  'Tubarões e Raias',
  'Invertebrados de Água Doce',
  'Invertebrados Marinhos',
];

/// Classe, como a Lista a nomeia.
const classesAmeacadas = <String>[
  'Actinopterygii',
  'Elasmobranchii',
  'Bivalvia',
  'Demospongiae',
  'Gastropoda',
  'Insecta',
  'Malacostraca',
  'Rhabditophora',
  'Anthozoa',
  'Asteroidea',
  'Echinoidea',
  'Holothuroidea',
  'Hydrozoa',
  'Polychaeta',
];

/// Uma linha da Lista Nacional Oficial.
class Ameacada {
  /// O número do item na Lista.
  final int n;
  final String especie;
  final String familia;
  final String ordem;

  /// Índice em [classesAmeacadas].
  final int classe;

  /// Índice em [gruposAmeacadas].
  final int grupo;

  /// 'CR', 'EN' ou 'VU', como a Lista escreve.
  final String cat;

  /// O asterisco impresso ao lado do número, sem legenda no DOU.
  final bool marca;

  /// Nome comum da Portaria MMA nº 445/2014, revogada. Só para busca.
  /// Vazio quando a 445 não trazia a espécie ou dizia "Desconhecido".
  final String pop445;

  const Ameacada(this.n, this.especie, this.familia, this.ordem, this.classe,
      this.grupo, this.cat, this.marca, [this.pop445 = '']);

  String get categoriaPorExtenso => switch (cat) {
        'CR' => 'Criticamente em Perigo',
        'EN' => 'Em Perigo',
        'VU' => 'Vulnerável',
        _ => '',
      };

  String get grupoPorExtenso => gruposAmeacadas[grupo];
  String get classePorExtenso => classesAmeacadas[classe];

  /// Gênero, para agrupar espécies do mesmo gênero na busca.
  String get genero => especie.split(' ').first;
}

/// As 490 espécies da Lista, na ordem do Anexo I.
const listaAmeacadas = <Ameacada>[
  Ameacada(1, 'Odontesthes bicudo', 'Atherinopsidae', 'Atheriniformes', 0, 0, 'EN', false, 'Peixe-rei'),
  Ameacada(2, 'Hypomasticus santanai', 'Anostomidae', 'Characiformes', 0, 0, 'EN', true),
  Ameacada(3, 'Leporinus guttatus', 'Anostomidae', 'Characiformes', 0, 0, 'EN', false, 'Aracu'),
  Ameacada(4, 'Leporinus pitingai', 'Anostomidae', 'Characiformes', 0, 0, 'EN', false, 'Aracu'),
  Ameacada(5, 'Megaleporinus gaiero', 'Anostomidae', 'Characiformes', 0, 0, 'VU', true),
  Ameacada(6, 'Sartor tucuruiensis', 'Anostomidae', 'Characiformes', 0, 0, 'EN', false),
  Ameacada(7, 'Brycon dulcis', 'Bryconidae', 'Characiformes', 0, 0, 'VU', true),
  Ameacada(8, 'Brycon gouldingi', 'Bryconidae', 'Characiformes', 0, 0, 'VU', false, 'Matrinxã'),
  Ameacada(9, 'Brycon orbignyanus', 'Bryconidae', 'Characiformes', 0, 0, 'CR', false, 'Piracanjuba'),
  Ameacada(10, 'Brycon vermelha', 'Bryconidae', 'Characiformes', 0, 0, 'EN', false, 'Vermelha'),
  Ameacada(11, 'Brycon vonoi', 'Bryconidae', 'Characiformes', 0, 0, 'EN', true),
  Ameacada(12, 'Astyanax brucutu', 'Characidae', 'Characiformes', 0, 0, 'CR', true),
  Ameacada(13, 'Astyanax eremus', 'Characidae', 'Characiformes', 0, 0, 'CR', false, 'Lambari'),
  Ameacada(14, 'Hasemania maxillaris', 'Characidae', 'Characiformes', 0, 0, 'CR', false),
  Ameacada(15, 'Hasemania melanura', 'Characidae', 'Characiformes', 0, 0, 'CR', false),
  Ameacada(16, 'Hasemania piatan', 'Characidae', 'Characiformes', 0, 0, 'EN', false),
  Ameacada(17, 'Hollandichthys taramandahy', 'Characidae', 'Characiformes', 0, 0, 'VU', false, 'Lambari-listrado'),
  Ameacada(18, 'Hyphessobrycon cantoi', 'Acestrorhamphidae', 'Characiformes', 0, 0, 'EN', true),
  Ameacada(19, 'Hyphessobrycon duragenys', 'Characidae', 'Characiformes', 0, 0, 'EN', false, 'Lambari'),
  Ameacada(20, 'Hyphessobrycon flammeus', 'Characidae', 'Characiformes', 0, 0, 'EN', false, 'Tetra-vermelho'),
  Ameacada(21, 'Hyphessobrycon taurocephalus', 'Characidae', 'Characiformes', 0, 0, 'CR', false),
  Ameacada(22, 'Hyphessobrycon veredus', 'Characidae', 'Characiformes', 0, 0, 'EN', true),
  Ameacada(23, 'Knodus dorsomaculatus', 'Stevardiidae', 'Characiformes', 0, 0, 'EN', true),
  Ameacada(24, 'Kolpotocheirodon figueiredoi', 'Characidae', 'Characiformes', 0, 0, 'CR', false),
  Ameacada(25, 'Lepidocharax diamantina', 'Characidae', 'Characiformes', 0, 0, 'EN', false),
  Ameacada(26, 'Mimagoniates lateralis', 'Characidae', 'Characiformes', 0, 0, 'VU', false, 'Lambari-azul-listrado'),
  Ameacada(27, 'Mimagoniates sylvicola', 'Characidae', 'Characiformes', 0, 0, 'EN', false, 'Piaba'),
  Ameacada(28, 'Moenkhausia parecis', 'Acestrorhamphidae', 'Characiformes', 0, 0, 'EN', true),
  Ameacada(29, 'Nematocharax varii', 'Characidae', 'Characiformes', 0, 0, 'EN', true),
  Ameacada(30, 'Psalidodon crenuchoides', 'Characidae', 'Characiformes', 0, 0, 'EN', false),
  Ameacada(31, 'Psalidodon uberaba', 'Characidae', 'Characiformes', 0, 0, 'EN', false),
  Ameacada(32, 'Rachoviscus crassiceps', 'Characidae', 'Characiformes', 0, 0, 'VU', false, 'Lambari-da-restinga'),
  Ameacada(33, 'Rachoviscus graciliceps', 'Characidae', 'Characiformes', 0, 0, 'EN', false, 'Lambari'),
  Ameacada(34, 'Spintherobolus ankoseion', 'Characidae', 'Characiformes', 0, 0, 'VU', false, 'Lambari'),
  Ameacada(35, 'Stygichthys typhlops', 'Characidae', 'Characiformes', 0, 0, 'CR', false, 'Piaba-branca'),
  Ameacada(36, 'Characidium onca', 'Crenuchidae', 'Characiformes', 0, 0, 'EN', true),
  Ameacada(37, 'Characidium vestigipinne', 'Crenuchidae', 'Characiformes', 0, 0, 'EN', false),
  Ameacada(38, 'Cyphocharax jagunco', 'Curimatidae', 'Characiformes', 0, 0, 'CR', true),
  Ameacada(39, 'Lebiasina marilynae', 'Lebiasinidae', 'Characiformes', 0, 0, 'VU', false),
  Ameacada(40, 'Lebiasina minuta', 'Lebiasinidae', 'Characiformes', 0, 0, 'VU', false),
  Ameacada(41, 'Prochilodus britskii', 'Prochilodontidae', 'Characiformes', 0, 0, 'VU', false, 'Curimatã'),
  Ameacada(42, 'Prochilodus harttii', 'Prochilodontidae', 'Characiformes', 0, 0, 'VU', true),
  Ameacada(43, 'Prochilodus vimboides', 'Prochilodontidae', 'Characiformes', 0, 0, 'VU', false),
  Ameacada(44, 'Colossoma macropomum', 'Serrasalmidae', 'Characiformes', 0, 0, 'VU', true),
  Ameacada(45, 'Crenicichla jupiaensis', 'Cichlidae', 'Cichliformes', 0, 0, 'EN', false, 'Joaninha'),
  Ameacada(46, 'Teleocichla centisquama', 'Cichlidae', 'Cichliformes', 0, 0, 'VU', false),
  Ameacada(47, 'Wallaciia urosema', 'Cichlidae', 'Cichliformes', 0, 0, 'VU', false),
  Ameacada(48, 'Jenynsia sanctaecatarinae', 'Anablepidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(49, 'Cnesterodon carnegiei', 'Poeciliidae', 'Cyprinodontiformes', 0, 0, 'VU', false, 'Barrigudinho'),
  Ameacada(50, 'Cnesterodon omorgmatos', 'Poeciliidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Barrigudinho'),
  Ameacada(51, 'Phalloptychus eigenmanni', 'Poeciliidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Barrigudinho'),
  Ameacada(52, 'Phalloptychus iheringii', 'Poeciliidae', 'Cyprinodontiformes', 0, 0, 'VU', true),
  Ameacada(53, 'Phallotorynus fasciolatus', 'Poeciliidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Barrigudinho'),
  Ameacada(54, 'Poecilia akroa', 'Poeciliidae', 'Cyprinodontiformes', 0, 0, 'EN', true),
  Ameacada(55, 'Poecilia pertapeh', 'Poeciliidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(56, 'Acrolebias carvalhoi', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(57, 'Anablepsoides cearensis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false, 'Peixe-anual'),
  Ameacada(58, 'Atlantirivulus lazzarotoi', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(59, 'Atlantirivulus maricensis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(60, 'Atlantirivulus nudiventris', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(61, 'Atlantirivulus simplicis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(62, 'Acantholebias quirogai', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(63, 'Austrolebias ephemerus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(64, 'Austrolebias univentripinnis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(65, 'Amatolebias varzeae', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(66, 'Campellolebias brucei', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(67, 'Campellolebias chrysolineatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(68, 'Campellolebias dorsimaculatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(69, 'Campellolebias intermedius', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(70, 'Cynolebias akroa', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false),
  Ameacada(71, 'Cynolebias elegans', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(72, 'Cynolebias gorutuba', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(73, 'Cynolebias griseus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-da-chuva'),
  Ameacada(74, 'Cynolebias leptocephalus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(75, 'Cynolebias parnaibensis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(76, 'Cynopoecilus feltrini', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false),
  Ameacada(77, 'Cynopoecilus intimus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(78, 'Cypholebias cinereus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(79, 'Garcialebias adloffi', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(80, 'Garcialebias arachan', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false),
  Ameacada(81, 'Garcialebias araucarianus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false),
  Ameacada(82, 'Garcialebias bagual', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(83, 'Garcialebias botocudo', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', true),
  Ameacada(84, 'Garcialebias cheffei', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', true),
  Ameacada(85, 'Garcialebias lourenciano', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', true),
  Ameacada(86, 'Garcialebias nachtigalli', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false),
  Ameacada(87, 'Garcialebias nigrofasciatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(88, 'Garcialebias nubium', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', true),
  Ameacada(89, 'Garcialebias pelotapes', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(90, 'Garcialebias pongondo', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(91, 'Garcialebias reicherti', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', true),
  Ameacada(92, 'Gymnolebias jaegari', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(93, 'Hypsolebias adornatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(94, 'Hypsolebias alternatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(95, 'Hypsolebias auratus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(96, 'Hypsolebias brunoi', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false, 'Peixe-anual'),
  Ameacada(97, 'Hypsolebias carlettoi', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(98, 'Hypsolebias delucai', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false),
  Ameacada(99, 'Hypsolebias faouri', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false),
  Ameacada(100, 'Hypsolebias fasciatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false, 'Peixe-anual'),
  Ameacada(101, 'Hypsolebias flammeus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false, 'Peixe-da-chuva'),
  Ameacada(102, 'Hypsolebias flavicaudatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(103, 'Hypsolebias fulminantis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(104, 'Hypsolebias gardneri', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(105, 'Hypsolebias ghisolfii', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(106, 'Hypsolebias gibberatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false, 'Peixe-anual'),
  Ameacada(107, 'Hypsolebias gilbertobrasili', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(108, 'Hypsolebias guanambi', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false, 'Peixe-anual'),
  Ameacada(109, 'Hypsolebias hamadryades', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(110, 'Hypsolebias harmonicus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false, 'Peixe-anual'),
  Ameacada(111, 'Hypsolebias hellneri', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(112, 'Hypsolebias igneus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(113, 'Hypsolebias janaubensis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(114, 'Hypsolebias longignatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false, 'Peixe-anual'),
  Ameacada(115, 'Hypsolebias lopesi', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(116, 'Hypsolebias macaubensis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(117, 'Hypsolebias magnificus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(118, 'Hypsolebias marginatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-da-chuva'),
  Ameacada(119, 'Hypsolebias mediopapillatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false, 'Peixe-anual'),
  Ameacada(120, 'Hypsolebias multiradiatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-da-chuva'),
  Ameacada(121, 'Hypsolebias nielseni', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(122, 'Hypsolebias notatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-da-chuva'),
  Ameacada(123, 'Hypsolebias nudiorbitatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false),
  Ameacada(124, 'Hypsolebias picturatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(125, 'Hypsolebias radiosus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', true),
  Ameacada(126, 'Hypsolebias radiseriatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(127, 'Hypsolebias rufus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(128, 'Hypsolebias shibattai', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false),
  Ameacada(129, 'Hypsolebias splendissimus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false),
  Ameacada(130, 'Hypsolebias stellatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(131, 'Hypsolebias tocantinensis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(132, 'Hypsolebias trilineatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(133, 'Hypsolebias virgulatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(134, 'Kryptolebias brasiliensis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(135, 'Kryptolebias gracilis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(136, 'Leptolebias marmoratus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(137, 'Leptopanchax citrinipinnis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(138, 'Leptopanchax itanhaensis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(139, 'Leptopanchax opalescens', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(140, 'Leptopanchax sanguineus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', true),
  Ameacada(141, 'Leptopanchax splendens', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(142, 'Maratecoara formosa', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-da-chuva'),
  Ameacada(143, 'Maratecoara splendida', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(144, 'Matilebias alexandri', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(145, 'Matilebias camaquensis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(146, 'Matilebias cyaneus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(147, 'Matilebias ibicuiensis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(148, 'Matilebias litzi', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false),
  Ameacada(149, 'Matilebias paucisquama', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false),
  Ameacada(150, 'Melanorivulus amambaiensis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', true),
  Ameacada(151, 'Melanorivulus egens', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', true),
  Ameacada(152, 'Melanorivulus interruptus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', true),
  Ameacada(153, 'Melanorivulus leali', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', true),
  Ameacada(154, 'Melanorivulus linearis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', true),
  Ameacada(155, 'Melanorivulus paracatuensis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', true),
  Ameacada(156, 'Melanorivulus pinima', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(157, 'Melanorivulus rutilicaudus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false, 'Peixe-anual'),
  Ameacada(158, 'Melanorivulus vittatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(159, 'Moema piriana', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(160, 'Nematolebias catimbau', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(161, 'Nematolebias papilliferus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(162, 'Nematolebias whitei', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(163, 'Notholebias cruzi', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(164, 'Notholebias fractifasciatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(165, 'Notholebias minimus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(166, 'Notholebias vermiculatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(167, 'Ophthalmolebias bokermanni', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(168, 'Ophthalmolebias constanciae', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(169, 'Ophthalmolebias ilheusensis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(170, 'Ophthalmolebias perpendicularis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(171, 'Ophthalmolebias rosaceus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(172, 'Ophthalmolebias suzarti', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false, 'Peixe-anual'),
  Ameacada(173, 'Pituna brevirostrata', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(174, 'Plesiolebias xavantei', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(175, 'Simpsonichthys boitonei', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(176, 'Simpsonichthys cholopteryx', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(177, 'Simpsonichthys espinhacensis', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(178, 'Simpsonichthys nigromaculatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'VU', false, 'Peixe-da-chuva'),
  Ameacada(179, 'Simpsonichthys parallelus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(180, 'Simpsonichthys punctulatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(181, 'Simpsonichthys santanae', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(182, 'Simpsonichthys zonatus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false, 'Peixe-anual'),
  Ameacada(183, 'Titanolebias cheradophilus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'CR', false),
  Ameacada(184, 'Trigonectes strigabundus', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false),
  Ameacada(185, 'Xenurolebias myersi', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', false, 'Peixe-anual'),
  Ameacada(186, 'Xenurolebias pataxo', 'Rivulidae', 'Cyprinodontiformes', 0, 0, 'EN', true),
  Ameacada(187, 'Sternarchogiton zuanoni', 'Apteronotidae', 'Gymnotiformes', 0, 0, 'EN', false),
  Ameacada(188, 'Sternarchorhynchus caboclo', 'Apteronotidae', 'Gymnotiformes', 0, 0, 'VU', false),
  Ameacada(189, 'Sternarchorhynchus higuchii', 'Apteronotidae', 'Gymnotiformes', 0, 0, 'CR', false),
  Ameacada(190, 'Sternarchorhynchus inpai', 'Apteronotidae', 'Gymnotiformes', 0, 0, 'VU', false),
  Ameacada(191, 'Sternarchorhynchus jaimei', 'Apteronotidae', 'Gymnotiformes', 0, 0, 'CR', false),
  Ameacada(192, 'Sternarchorhynchus kokraimoro', 'Apteronotidae', 'Gymnotiformes', 0, 0, 'EN', false),
  Ameacada(193, 'Sternarchorhynchus mareikeae', 'Apteronotidae', 'Gymnotiformes', 0, 0, 'VU', false),
  Ameacada(194, 'Sternarchorhynchus severii', 'Apteronotidae', 'Gymnotiformes', 0, 0, 'VU', false, 'Ituí'),
  Ameacada(195, 'Sternarchorhynchus villasboasi', 'Apteronotidae', 'Gymnotiformes', 0, 0, 'EN', false),
  Ameacada(196, 'Archolaemus ferreirai', 'Sternopygidae', 'Gymnotiformes', 0, 0, 'VU', false),
  Ameacada(197, 'Archolaemus santosi', 'Sternopygidae', 'Gymnotiformes', 0, 0, 'VU', false),
  Ameacada(198, 'Eigenmannia vicentespelaea', 'Sternopygidae', 'Gymnotiformes', 0, 0, 'EN', false, 'Ituí'),
  Ameacada(199, 'Paragenidens grandoculis', 'Ariidae', 'Siluriformes', 0, 0, 'CR', false),
  Ameacada(200, 'Aspidoras mephisto', 'Callichthyidae', 'Siluriformes', 0, 0, 'CR', true),
  Ameacada(201, 'Chasmocranus brachynemus', 'Heptapteridae', 'Siluriformes', 0, 0, 'EN', false),
  Ameacada(202, 'Heptapterus multiradiatus', 'Heptapteridae', 'Siluriformes', 0, 0, 'CR', false, 'Bagrinho-do-tietê'),
  Ameacada(203, 'Pimelodella kronei', 'Heptapteridae', 'Siluriformes', 0, 0, 'EN', false, 'Bagre-cego-de-iporanga'),
  Ameacada(204, 'Pimelodella spelaea', 'Heptapteridae', 'Siluriformes', 0, 0, 'VU', false),
  Ameacada(205, 'Rhamdia enfurnada', 'Heptapteridae', 'Siluriformes', 0, 0, 'VU', true),
  Ameacada(206, 'Rhamdiopsis krugi', 'Heptapteridae', 'Siluriformes', 0, 0, 'EN', false, 'Bagrinho-cego'),
  Ameacada(207, 'Ancistrus cryptophthalmus', 'Loricariidae', 'Siluriformes', 0, 0, 'EN', false, 'Cascudinho-de-caverna'),
  Ameacada(208, 'Ancistrus formoso', 'Loricariidae', 'Siluriformes', 0, 0, 'EN', false, 'Cascudo-cego'),
  Ameacada(209, 'Ancistrus minutus', 'Loricariidae', 'Siluriformes', 0, 0, 'EN', false),
  Ameacada(210, 'Baryancistrus longipinnis', 'Loricariidae', 'Siluriformes', 0, 0, 'EN', false),
  Ameacada(211, 'Baryancistrus niveatus', 'Loricariidae', 'Siluriformes', 0, 0, 'VU', false, 'Acari'),
  Ameacada(212, 'Delturus parahybae', 'Loricariidae', 'Siluriformes', 0, 0, 'CR', false, 'Cascudo'),
  Ameacada(213, 'Eurycheilichthys apocremnus', 'Loricariidae', 'Siluriformes', 0, 0, 'CR', true),
  Ameacada(214, 'Harttia depressa', 'Loricariidae', 'Siluriformes', 0, 0, 'EN', false, 'Acari-cachimbo'),
  Ameacada(215, 'Harttia panara', 'Loricariidae', 'Siluriformes', 0, 0, 'VU', false),
  Ameacada(216, 'Harttia villasboas', 'Loricariidae', 'Siluriformes', 0, 0, 'VU', false),
  Ameacada(217, 'Hemiancistrus megalopteryx', 'Loricariidae', 'Siluriformes', 0, 0, 'EN', false),
  Ameacada(218, 'Hypancistrus zebra', 'Loricariidae', 'Siluriformes', 0, 0, 'CR', false, 'Cascudo zebra imperial'),
  Ameacada(219, 'Hypostomus subcarinatus', 'Loricariidae', 'Siluriformes', 0, 0, 'CR', false),
  Ameacada(220, 'Isbrueckerichthys saxicola', 'Loricariidae', 'Siluriformes', 0, 0, 'EN', false, 'Cascudo'),
  Ameacada(221, 'Microlepidogaster perforata', 'Loricariidae', 'Siluriformes', 0, 0, 'CR', false),
  Ameacada(222, 'Neoplecostomus botucatu', 'Loricariidae', 'Siluriformes', 0, 0, 'CR', false, 'Cascudo'),
  Ameacada(223, 'Otothyris juquiae', 'Loricariidae', 'Siluriformes', 0, 0, 'EN', false, 'Cascudinho-anão'),
  Ameacada(224, 'Parancistrus nudiventris', 'Loricariidae', 'Siluriformes', 0, 0, 'EN', false),
  Ameacada(225, 'Parotocinclus cesarpintoi', 'Loricariidae', 'Siluriformes', 0, 0, 'EN', true),
  Ameacada(226, 'Parotocinclus seridoensis', 'Loricariidae', 'Siluriformes', 0, 0, 'EN', true),
  Ameacada(227, 'Parotocinclus spilosoma', 'Loricariidae', 'Siluriformes', 0, 0, 'EN', true),
  Ameacada(228, 'Parotocinclus spilurus', 'Loricariidae', 'Siluriformes', 0, 0, 'EN', false, 'Cascudinho'),
  Ameacada(229, 'Plesioptopoma curvidens', 'Loricariidae', 'Siluriformes', 0, 0, 'CR', false),
  Ameacada(230, 'Pogonopoma obscurum', 'Loricariidae', 'Siluriformes', 0, 0, 'VU', false, 'Cascudo-preto'),
  Ameacada(231, 'Pogonopoma parahybae', 'Loricariidae', 'Siluriformes', 0, 0, 'EN', false, 'Cascudo'),
  Ameacada(232, 'Pseudotocinclus tietensis', 'Loricariidae', 'Siluriformes', 0, 0, 'EN', false, 'Cascudinho-do-tietê'),
  Ameacada(233, 'Conorhynchos conirostris', 'Pimelodidae', 'Siluriformes', 0, 0, 'EN', false, 'Pirá-tamanduá'),
  Ameacada(234, 'Pseudoplatystoma corruscans', 'Pimelodidae', 'Siluriformes', 0, 0, 'VU', false),
  Ameacada(235, 'Steindachneridion amblyurum', 'Pimelodidae', 'Siluriformes', 0, 0, 'VU', false, 'Surubim-do-Jequitinhonha'),
  Ameacada(236, 'Steindachneridion doceanum', 'Pimelodidae', 'Siluriformes', 0, 0, 'EN', false, 'Surubim-do-doce'),
  Ameacada(237, 'Steindachneridion melanodermatum', 'Pimelodidae', 'Siluriformes', 0, 0, 'EN', false, 'Surubim-do-iguaçu'),
  Ameacada(238, 'Steindachneridion parahybae', 'Pimelodidae', 'Siluriformes', 0, 0, 'EN', false, 'Surubim-do-paraíba'),
  Ameacada(239, 'Steindachneridion punctatum', 'Pimelodidae', 'Siluriformes', 0, 0, 'EN', true),
  Ameacada(240, 'Steindachneridion scriptum', 'Pimelodidae', 'Siluriformes', 0, 0, 'VU', false, 'Surubim'),
  Ameacada(241, 'Lophiosilurus alexandri', 'Pseudopimelodidae', 'Siluriformes', 0, 0, 'VU', false, 'Pacamã'),
  Ameacada(242, 'Microglanis maculatus', 'Pseudopimelodidae', 'Siluriformes', 0, 0, 'CR', false),
  Ameacada(243, 'Microglanis robustus', 'Pseudopimelodidae', 'Siluriformes', 0, 0, 'EN', false),
  Ameacada(244, 'Cambeva crassicaudata', 'Trichomycteridae', 'Siluriformes', 0, 0, 'EN', false),
  Ameacada(245, 'Cambeva igobi', 'Trichomycteridae', 'Siluriformes', 0, 0, 'VU', false),
  Ameacada(246, 'Cambeva mboycy', 'Trichomycteridae', 'Siluriformes', 0, 0, 'EN', false),
  Ameacada(247, 'Cambeva papillifera', 'Trichomycteridae', 'Siluriformes', 0, 0, 'EN', false),
  Ameacada(248, 'Cambeva pascuali', 'Trichomycteridae', 'Siluriformes', 0, 0, 'CR', false),
  Ameacada(249, 'Cambeva tropeiro', 'Trichomycteridae', 'Siluriformes', 0, 0, 'EN', false),
  Ameacada(250, 'Ituglanis bambui', 'Trichomycteridae', 'Siluriformes', 0, 0, 'CR', false, 'Bagrinho-de-caverna'),
  Ameacada(251, 'Ituglanis epikarsticus', 'Trichomycteridae', 'Siluriformes', 0, 0, 'CR', false, 'Bagrinho-de-caverna'),
  Ameacada(252, 'Ituglanis mambai', 'Trichomycteridae', 'Siluriformes', 0, 0, 'CR', false),
  Ameacada(253, 'Ituglanis passensis', 'Trichomycteridae', 'Siluriformes', 0, 0, 'CR', false, 'Bagrinho-de-caverna'),
  Ameacada(254, 'Ituglanis ramiroi', 'Trichomycteridae', 'Siluriformes', 0, 0, 'VU', false, 'Bagrinho-de-caverna'),
  Ameacada(255, 'Listrura depinnai', 'Trichomycteridae', 'Siluriformes', 0, 0, 'EN', true),
  Ameacada(256, 'Listrura nematopteryx', 'Trichomycteridae', 'Siluriformes', 0, 0, 'EN', false),
  Ameacada(257, 'Trichogenes claviger', 'Trichomycteridae', 'Siluriformes', 0, 0, 'EN', false),
  Ameacada(258, 'Trichomycterus dali', 'Trichomycteridae', 'Siluriformes', 0, 0, 'EN', false, 'Bagrinho-cego-da-serra-da-bodoquena'),
  Ameacada(259, 'Trichomycterus itacarambiensis', 'Trichomycteridae', 'Siluriformes', 0, 0, 'VU', false),
  Ameacada(260, 'Trichomycterus rubbioli', 'Trichomycteridae', 'Siluriformes', 0, 0, 'VU', false),
  Ameacada(261, 'Megalops atlanticus', 'Megalopidae', 'Elopiformes', 0, 1, 'VU', false, 'Amaripim'),
  Ameacada(262, 'Acyrtus pauciradiatus', 'Gobiesocidae', 'Gobiesociformes', 0, 1, 'VU', true),
  Ameacada(263, 'Otophidium chickcharney', 'Ophidiidae', 'Ophidiiformes', 0, 1, 'CR', false),
  Ameacada(264, 'Hypleurochilus brasil', 'Blenniidae', 'Perciformes', 0, 1, 'VU', true),
  Ameacada(265, 'Scartella itajobi', 'Blenniidae', 'Perciformes', 0, 1, 'VU', true),
  Ameacada(266, 'Scartella poiti', 'Blenniidae', 'Perciformes', 0, 1, 'VU', true),
  Ameacada(267, 'Prognathodes obliquus', 'Chaetodontidae', 'Perciformes', 0, 1, 'VU', false, 'Peixe-borboleta-de-são-pedro-e-são-paulo'),
  Ameacada(268, 'Epinephelus itajara', 'Epinephelidae', 'Perciformes', 0, 1, 'CR', false, 'Mero'),
  Ameacada(269, 'Epinephelus marginatus', 'Epinephelidae', 'Perciformes', 0, 1, 'VU', false, 'Garoupa verdadeira'),
  Ameacada(270, 'Epinephelus morio', 'Epinephelidae', 'Perciformes', 0, 1, 'EN', false, 'Garoupa'),
  Ameacada(271, 'Bathygobius brasiliensis', 'Gobiidae', 'Perciformes', 0, 1, 'VU', true),
  Ameacada(272, 'Elacatinus figaro', 'Gobiidae', 'Perciformes', 0, 1, 'EN', false, 'Neon'),
  Ameacada(273, 'Elacatinus phthirophagus', 'Gobiidae', 'Perciformes', 0, 1, 'VU', true),
  Ameacada(274, 'Makaira nigricans', 'Istiophoridae', 'Perciformes', 0, 1, 'VU', false, 'Marlin-azul'),
  Ameacada(275, 'Halichoeres rubrovirens', 'Labridae', 'Perciformes', 0, 1, 'VU', false, 'Budião-fogueira'),
  Ameacada(276, 'Malacoctenus brunoi', 'Labrisomidae', 'Perciformes', 0, 1, 'VU', false),
  Ameacada(277, 'Starksia multilepis', 'Labrisomidae', 'Perciformes', 0, 1, 'VU', true),
  Ameacada(278, 'Lutjanus cyanopterus', 'Lutjanidae', 'Perciformes', 0, 1, 'VU', false, 'Caranha'),
  Ameacada(279, 'Lutjanus purpureus', 'Lutjanidae', 'Perciformes', 0, 1, 'EN', false, 'Pargo'),
  Ameacada(280, 'Lopholatilus villarii', 'Latilidae', 'Acanthuriformes', 0, 1, 'VU', false, 'Peixe-batata'),
  Ameacada(281, 'Cerdale fasciata', 'Gobiidae', 'Gobiiformes', 0, 1, 'EN', false, 'Peixe-lombriga-listrado'),
  Ameacada(282, 'Pempheris gasparinii', 'Pempheridae', 'Perciformes', 0, 1, 'VU', true),
  Ameacada(283, 'Polyprion americanus', 'Polyprionidae', 'Acropomatiformes', 0, 1, 'CR', false, 'Cherne-poveiro'),
  Ameacada(284, 'Microspathodon chrysurus', 'Pomacentridae', 'Perciformes', 0, 1, 'VU', false, 'Donzela-azul'),
  Ameacada(285, 'Stegastes rocasensis', 'Pomacentridae', 'Perciformes', 0, 1, 'VU', false, 'Donzela-de-rocas'),
  Ameacada(286, 'Stegastes sanctipauli', 'Pomacentridae', 'Perciformes', 0, 1, 'VU', false, 'Donzela-de-são-pedro'),
  Ameacada(287, 'Stegastes trindadensis', 'Pomacentridae', 'Perciformes', 0, 1, 'VU', false),
  Ameacada(288, 'Scarus trispinosus', 'Scaridae', 'Perciformes', 0, 1, 'CR', false, 'Budião-azul'),
  Ameacada(289, 'Scarus zelindae', 'Scaridae', 'Perciformes', 0, 1, 'EN', false, 'Peixe-papagaio-banana'),
  Ameacada(290, 'Sparisoma amplum', 'Scaridae', 'Perciformes', 0, 1, 'VU', true),
  Ameacada(291, 'Sparisoma axillare', 'Scaridae', 'Perciformes', 0, 1, 'VU', false, 'Peixe-papagaio-cinza'),
  Ameacada(292, 'Sparisoma frondosum', 'Scaridae', 'Perciformes', 0, 1, 'VU', false, 'Peixe-papagaio-cinza'),
  Ameacada(293, 'Sparisoma rocha', 'Scaridae', 'Perciformes', 0, 1, 'VU', false, 'Budião-de-trindade'),
  Ameacada(294, 'Pogonias courbina', 'Sciaenidae', 'Acanthuriformes', 0, 1, 'CR', false),
  Ameacada(295, 'Thunnus thynnus', 'Scombridae', 'Perciformes', 0, 1, 'EN', false, 'Atum-azul'),
  Ameacada(296, 'Choranthias salmopunctatus', 'Anthiadidae', 'Perciformes', 0, 1, 'VU', false),
  Ameacada(297, 'Hyporthodus flavolimbatus', 'Epinephelidae', 'Perciformes', 0, 1, 'EN', true),
  Ameacada(298, 'Hyporthodus nigritus', 'Epinephelidae', 'Perciformes', 0, 1, 'EN', false, 'Cherne-negro'),
  Ameacada(299, 'Hyporthodus niveatus', 'Epinephelidae', 'Perciformes', 0, 1, 'VU', false, 'Cherne-verdadeiro'),
  Ameacada(300, 'Mycteroperca acutirostris', 'Epinephelidae', 'Perciformes', 0, 1, 'EN', true),
  Ameacada(301, 'Mycteroperca bonaci', 'Epinephelidae', 'Perciformes', 0, 1, 'EN', false, 'Sirigado'),
  Ameacada(302, 'Mycteroperca interstitialis', 'Epinephelidae', 'Perciformes', 0, 1, 'VU', false, 'Badejo-amarelo'),
  Ameacada(303, 'Odontanthias cauoh', 'Anthiadidae', 'Perciformes', 0, 1, 'VU', true),
  Ameacada(304, 'Tosanoides aphrodite', 'Anthiadidae', 'Perciformes', 0, 1, 'VU', true),
  Ameacada(305, 'Enneanectes smithi', 'Tripterygiidae', 'Blenniiformes', 0, 1, 'VU', false),
  Ameacada(306, 'Achirus mucuri', 'Achiridae', 'Pleuronectiformes', 0, 1, 'EN', false, 'Solha'),
  Ameacada(307, 'Genidens barbus', 'Ariidae', 'Siluriformes', 0, 1, 'EN', false, 'Bagre-branco'),
  Ameacada(308, 'Genidens planifrons', 'Ariidae', 'Siluriformes', 0, 1, 'EN', false, 'Bagre-marinho'),
  Ameacada(309, 'Sciades parkeri', 'Ariidae', 'Siluriformes', 0, 1, 'VU', false, 'Gurijuba'),
  Ameacada(310, 'Hippocampus erectus', 'Syngnathidae', 'Syngnathiformes', 0, 1, 'VU', false, 'Cavalo-marinho'),
  Ameacada(311, 'Hippocampus patagonicus', 'Syngnathidae', 'Syngnathiformes', 0, 1, 'VU', false, 'Cavalo-marinho'),
  Ameacada(312, 'Hippocampus reidi', 'Syngnathidae', 'Syngnathiformes', 0, 1, 'VU', false, 'Cavalo-marinho'),
  Ameacada(313, 'Balistes capriscus', 'Balistidae', 'Tetraodontiformes', 0, 1, 'EN', true),
  Ameacada(314, 'Carcharhinus acronotus', 'Carcharhinidae', 'Carcharhiniformes', 1, 2, 'VU', false),
  Ameacada(315, 'Carcharhinus brevipinna', 'Carcharhinidae', 'Carcharhiniformes', 1, 2, 'VU', false),
  Ameacada(316, 'Carcharhinus falciformis', 'Carcharhinidae', 'Carcharhiniformes', 1, 2, 'CR', false),
  Ameacada(317, 'Carcharhinus galapagensis', 'Carcharhinidae', 'Carcharhiniformes', 1, 2, 'CR', false, 'Tubarão-das-galápagos'),
  Ameacada(318, 'Carcharhinus leucas', 'Carcharhinidae', 'Carcharhiniformes', 1, 2, 'VU', false),
  Ameacada(319, 'Carcharhinus longimanus', 'Carcharhinidae', 'Carcharhiniformes', 1, 2, 'CR', false, 'Tubarão-galha-branca'),
  Ameacada(320, 'Carcharhinus obscurus', 'Carcharhinidae', 'Carcharhiniformes', 1, 2, 'EN', false, 'Cação-fidalgo'),
  Ameacada(321, 'Carcharhinus perezi', 'Carcharhinidae', 'Carcharhiniformes', 1, 2, 'VU', false, 'Tubarão-dos-recifes'),
  Ameacada(322, 'Carcharhinus plumbeus', 'Carcharhinidae', 'Carcharhiniformes', 1, 2, 'CR', false, 'Tubarão-galhudo'),
  Ameacada(323, 'Carcharhinus porosus', 'Carcharhinidae', 'Carcharhiniformes', 1, 2, 'CR', false, 'Cação-azeiteiro'),
  Ameacada(324, 'Carcharhinus signatus', 'Carcharhinidae', 'Carcharhiniformes', 1, 2, 'EN', false, 'Cação-noturno'),
  Ameacada(325, 'Isogomphodon oxyrhynchus', 'Carcharhinidae', 'Carcharhiniformes', 1, 2, 'CR', false, 'Cação-quati'),
  Ameacada(326, 'Negaprion brevirostris', 'Carcharhinidae', 'Carcharhiniformes', 1, 2, 'EN', false, 'Tubarão-limão'),
  Ameacada(327, 'Sphyrna gilberti', 'Sphyrnidae', 'Carcharhiniformes', 1, 2, 'CR', true),
  Ameacada(328, 'Sphyrna lewini', 'Sphyrnidae', 'Carcharhiniformes', 1, 2, 'CR', false, 'Tubarão-martelo'),
  Ameacada(329, 'Sphyrna media', 'Sphyrnidae', 'Carcharhiniformes', 1, 2, 'CR', false, 'Tubarão-martelo-de-aba-curta'),
  Ameacada(330, 'Sphyrna mokarran', 'Sphyrnidae', 'Carcharhiniformes', 1, 2, 'CR', false, 'Tubarão-martelo-grande'),
  Ameacada(331, 'Sphyrna tiburo', 'Sphyrnidae', 'Carcharhiniformes', 1, 2, 'CR', false, 'Tubarão-martelo'),
  Ameacada(332, 'Sphyrna tudes', 'Sphyrnidae', 'Carcharhiniformes', 1, 2, 'CR', false, 'Tubarão-martelo'),
  Ameacada(333, 'Sphyrna zygaena', 'Sphyrnidae', 'Carcharhiniformes', 1, 2, 'CR', false, 'Tubarão-martelo-liso'),
  Ameacada(334, 'Galeorhinus galeus', 'Triakidae', 'Carcharhiniformes', 1, 2, 'CR', false, 'Cação-bico-doce'),
  Ameacada(335, 'Mustelus canis', 'Triakidae', 'Carcharhiniformes', 1, 2, 'EN', false, 'Boca-de-velha'),
  Ameacada(336, 'Mustelus fasciatus', 'Triakidae', 'Carcharhiniformes', 1, 2, 'CR', false, 'Cação-listrado'),
  Ameacada(337, 'Mustelus schmitti', 'Triakidae', 'Carcharhiniformes', 1, 2, 'CR', false, 'Tubarão-bico-doce-pintado'),
  Ameacada(338, 'Notorynchus cepedianus', 'Hexanchidae', 'Hexanchiformes', 1, 2, 'CR', false, 'Cação-bruxa'),
  Ameacada(339, 'Alopias superciliosus', 'Alopiidae', 'Lamniformes', 1, 2, 'EN', false, 'Tubarão-raposa'),
  Ameacada(340, 'Alopias vulpinus', 'Alopiidae', 'Lamniformes', 1, 2, 'CR', false, 'Tubarão-raposa'),
  Ameacada(341, 'Carcharias taurus', 'Carchariidae', 'Lamniformes', 1, 2, 'CR', false, 'Cação-mangona'),
  Ameacada(342, 'Cetorhinus maximus', 'Cetorhinidae', 'Lamniformes', 1, 2, 'CR', false, 'Tubarão-peregrino'),
  Ameacada(343, 'Carcharodon carcharias', 'Lamnidae', 'Lamniformes', 1, 2, 'VU', false, 'Tubarão-branco'),
  Ameacada(344, 'Isurus oxyrinchus', 'Lamnidae', 'Lamniformes', 1, 2, 'CR', false),
  Ameacada(345, 'Bathytoshia centroura', 'Dasyatidae', 'Myliobatiformes', 1, 2, 'CR', false),
  Ameacada(346, 'Fontitrygon colarensis', 'Dasyatidae', 'Myliobatiformes', 1, 2, 'VU', false),
  Ameacada(347, 'Hypanus berthalutzae', 'Dasyatidae', 'Myliobatiformes', 1, 2, 'VU', false),
  Ameacada(348, 'Hypanus marianae', 'Dasyatidae', 'Myliobatiformes', 1, 2, 'VU', false),
  Ameacada(349, 'Gymnura altavela', 'Gymnuridae', 'Myliobatiformes', 1, 2, 'CR', false, 'Raia-manteiga'),
  Ameacada(350, 'Mobula birostris', 'Mobulidae', 'Myliobatiformes', 1, 2, 'VU', false),
  Ameacada(351, 'Mobula mobular', 'Mobulidae', 'Myliobatiformes', 1, 2, 'VU', false),
  Ameacada(352, 'Mobula tarapacana', 'Mobulidae', 'Myliobatiformes', 1, 2, 'VU', false, 'Raia-manta'),
  Ameacada(353, 'Mobula thurstoni', 'Mobulidae', 'Myliobatiformes', 1, 2, 'VU', false, 'Raia-manta'),
  Ameacada(354, 'Myliobatis freminvillei', 'Myliobatidae', 'Myliobatiformes', 1, 2, 'EN', false),
  Ameacada(355, 'Myliobatis goodei', 'Myliobatidae', 'Myliobatiformes', 1, 2, 'CR', false, 'Raia-sapo'),
  Ameacada(356, 'Myliobatis ridens', 'Myliobatidae', 'Myliobatiformes', 1, 2, 'CR', false, 'Raia-manteiga'),
  Ameacada(357, 'Paratrygon aiereba', 'Potamotrygonidae', 'Myliobatiformes', 1, 2, 'CR', false, 'Arraia-aramaçá'),
  Ameacada(358, 'Potamotrygon leopoldi', 'Potamotrygonidae', 'Myliobatiformes', 1, 2, 'VU', true),
  Ameacada(359, 'Potamotrygon marquesi', 'Potamotrygonidae', 'Myliobatiformes', 1, 2, 'VU', true),
  Ameacada(360, 'Potamotrygon signata', 'Potamotrygonidae', 'Myliobatiformes', 1, 2, 'EN', true),
  Ameacada(361, 'Rhinoptera brasiliensis', 'Rhinopteridae', 'Myliobatiformes', 1, 2, 'CR', false, 'Raia-beiço-de-boi'),
  Ameacada(362, 'Urotrygon microphthalmum', 'Urotrygonidae', 'Myliobatiformes', 1, 2, 'VU', false),
  Ameacada(363, 'Ginglymostoma cirratum', 'Ginglymostomatidae', 'Orectolobiformes', 1, 2, 'VU', false, 'Tubarão-lixa'),
  Ameacada(364, 'Rhincodon typus', 'Rhincodontidae', 'Orectolobiformes', 1, 2, 'VU', false, 'Tubarão-baleia'),
  Ameacada(365, 'Atlantoraja castelnaui', 'Arhynchobatidae', 'Rajiformes', 1, 2, 'EN', false, 'Raia-chita'),
  Ameacada(366, 'Atlantoraja cyclophora', 'Arhynchobatidae', 'Rajiformes', 1, 2, 'VU', false),
  Ameacada(367, 'Rioraja agassizii', 'Arhynchobatidae', 'Rajiformes', 1, 2, 'VU', false, 'Raia-santa'),
  Ameacada(368, 'Sympterygia acuta', 'Arhynchobatidae', 'Rajiformes', 1, 2, 'EN', false, 'Raia-emplastro'),
  Ameacada(369, 'Sympterygia bonapartii', 'Arhynchobatidae', 'Rajiformes', 1, 2, 'EN', false, 'Emplastro-amarelo'),
  Ameacada(370, 'Pristis pectinata', 'Pristidae', 'Rhinopristiformes', 1, 2, 'CR', false, 'Peixe-serra'),
  Ameacada(371, 'Pristis pristis', 'Pristidae', 'Rhinopristiformes', 1, 2, 'CR', false, 'Peixe-serra'),
  Ameacada(372, 'Pseudobatos horkelii', 'Rhinobatidae', 'Rhinopristiformes', 1, 2, 'CR', false),
  Ameacada(373, 'Pseudobatos percellens', 'Rhinobatidae', 'Rhinopristiformes', 1, 2, 'VU', false),
  Ameacada(374, 'Zapteryx brevirostris', 'Trygonorhinidae', 'Rhinopristiformes', 1, 2, 'VU', false, 'Raia-viola'),
  Ameacada(375, 'Squatina argentina', 'Squatinidae', 'Squatiniformes', 1, 2, 'CR', false, 'Cação-anjo-de-asa-longa'),
  Ameacada(376, 'Squatina guggenheim', 'Squatinidae', 'Squatiniformes', 1, 2, 'CR', false, 'Cação-anjo-espinhudo'),
  Ameacada(377, 'Squatina occulta', 'Squatinidae', 'Squatiniformes', 1, 2, 'CR', false, 'Cação-anjo-de-asa-curta'),
  Ameacada(378, 'Narcine brasiliensis', 'Narcinidae', 'Torpediniformes', 1, 2, 'VU', false),
  Ameacada(379, 'Eupera troglobia', 'Sphaeriidae', 'Sphaeriida', 2, 3, 'CR', false),
  Ameacada(380, 'Castalia martensi', 'Hyriidae', 'Unionida', 2, 3, 'VU', true),
  Ameacada(381, 'Diplodon fontainianus', 'Hyriidae', 'Unionida', 2, 3, 'VU', true),
  Ameacada(382, 'Rhipidodonta garbei', 'Hyriidae', 'Unionida', 2, 3, 'VU', true),
  Ameacada(383, 'Rhipidodonta iheringi', 'Hyriidae', 'Unionida', 2, 3, 'EN', true),
  Ameacada(384, 'Rhipidodonta koseritzi', 'Hyriidae', 'Unionida', 2, 3, 'EN', false),
  Ameacada(385, 'Anodontites ferrarisii', 'Mycetopodidae', 'Unionida', 2, 3, 'EN', true),
  Ameacada(386, 'Anodontites iheringi', 'Mycetopodidae', 'Unionida', 2, 3, 'EN', true),
  Ameacada(387, 'Haasica balzani', 'Mycetopodidae', 'Unionida', 2, 3, 'VU', true),
  Ameacada(388, 'Leila blainvilliana', 'Mycetopodidae', 'Unionida', 2, 3, 'CR', true),
  Ameacada(389, 'Monocondylaea franciscana', 'Mycetopodidae', 'Unionida', 2, 3, 'VU', true),
  Ameacada(390, 'Monocondylaea paraguayana', 'Mycetopodidae', 'Unionida', 2, 3, 'VU', true),
  Ameacada(391, 'Mycetopoda legumen', 'Mycetopodidae', 'Unionida', 2, 3, 'EN', false, 'Faquinha-arredondada'),
  Ameacada(392, 'Cyanocyclas guahybensis', 'Cyrenidae', 'Venerida', 2, 3, 'EN', true),
  Ameacada(393, 'Racekiela cavernicola', 'Spongillidae', 'Spongillida', 3, 3, 'CR', false, 'Esponja'),
  Ameacada(394, 'Arinosaster patriciae', 'Incertae Sedis', 'Incertae Sedis', 3, 3, 'CR', true),
  Ameacada(395, 'Potamolithus troglobius', 'Hydrobiidae', 'Caenogastropoda', 4, 3, 'CR', false, 'Caramujo-de-caverna'),
  Ameacada(396, 'Potamolithus karsticus', 'Tateidae', 'Caenogastropoda', 4, 3, 'EN', false, 'Caramujo-de-caverna'),
  Ameacada(397, 'Aylacostoma tenuilabris', 'Thiaridae', 'Caenogastropoda', 4, 3, 'VU', true),
  Ameacada(398, 'Spiripockia punctata', 'Pomatiopsidae', 'Littorinimorpha', 4, 3, 'CR', false),
  Ameacada(399, 'Copelatus cessaima', 'Dytiscidae', 'Coleoptera', 5, 3, 'EN', false),
  Ameacada(400, 'Adebrotus lugoi', 'Baetidae', 'Ephemeroptera', 5, 3, 'VU', false),
  Ameacada(401, 'Camelobaetidius juparana', 'Baetidae', 'Ephemeroptera', 5, 3, 'VU', false),
  Ameacada(402, 'Camelobaetidius maranhensis', 'Baetidae', 'Ephemeroptera', 5, 3, 'VU', false),
  Ameacada(403, 'Camelobaetidius spinosus', 'Baetidae', 'Ephemeroptera', 5, 3, 'VU', false),
  Ameacada(404, 'Hermanella amere', 'Leptophlebiidae', 'Ephemeroptera', 5, 3, 'EN', false),
  Ameacada(405, 'Hermanella nigra', 'Leptophlebiidae', 'Ephemeroptera', 5, 3, 'VU', false),
  Ameacada(406, 'Miroculis stenopterus', 'Leptophlebiidae', 'Ephemeroptera', 5, 3, 'EN', true),
  Ameacada(407, 'Simothraulopsis eurybasis', 'Leptophlebiidae', 'Ephemeroptera', 5, 3, 'VU', false),
  Ameacada(408, 'Lachlania aldinae', 'Oligoneuriidae', 'Ephemeroptera', 5, 3, 'VU', true),
  Ameacada(409, 'Oligoneuria amandae', 'Oligoneuriidae', 'Ephemeroptera', 5, 3, 'VU', true),
  Ameacada(410, 'Oligoneuria macabaiba', 'Oligoneuriidae', 'Ephemeroptera', 5, 3, 'EN', true),
  Ameacada(411, 'Spelaeometra hypogea', 'Hydrometridae', 'Hemiptera', 5, 3, 'CR', true),
  Ameacada(412, 'Forcepsioneura machadorum', 'Coenagrionidae', 'Odonata', 5, 3, 'CR', true),
  Ameacada(413, 'Franciscobasis franciscoi', 'Coenagrionidae', 'Odonata', 5, 3, 'EN', true),
  Ameacada(414, 'Kiautagrion acutum', 'Coenagrionidae', 'Odonata', 5, 3, 'EN', false),
  Ameacada(415, 'Leptagrion bocainense', 'Coenagrionidae', 'Odonata', 5, 3, 'VU', false),
  Ameacada(416, 'Machadagrion garbei', 'Coenagrionidae', 'Odonata', 5, 3, 'VU', true),
  Ameacada(417, 'Minagrion canaanense', 'Coenagrionidae', 'Odonata', 5, 3, 'VU', true),
  Ameacada(418, 'Heteragrion mantiqueirae', 'Megapodagrionidae', 'Odonata', 5, 3, 'EN', true),
  Ameacada(419, 'Fluminagrion taxaense', 'Coenagrionidae', 'Zygoptera', 5, 3, 'CR', false),
  Ameacada(420, 'Spelaeogammarus bahiensis', 'Artesiidae', 'Amphipoda', 6, 3, 'VU', false),
  Ameacada(421, 'Spelaeogammarus ginae', 'Artesiidae', 'Amphipoda', 6, 3, 'CR', false),
  Ameacada(422, 'Spelaeogammarus sanctus', 'Artesiidae', 'Amphipoda', 6, 3, 'CR', false),
  Ameacada(423, 'Spelaeogammarus santanensis', 'Artesiidae', 'Amphipoda', 6, 3, 'CR', false),
  Ameacada(424, 'Spelaeogammarus spinilacertus', 'Artesiidae', 'Amphipoda', 6, 3, 'EN', false),
  Ameacada(425, 'Spelaeogammarus titan', 'Artesiidae', 'Amphipoda', 6, 3, 'CR', false),
  Ameacada(426, 'Spelaeogammarus trajanoae', 'Artesiidae', 'Amphipoda', 6, 3, 'EN', false),
  Ameacada(427, 'Megagidiella azul', 'Bogidiellidae', 'Amphipoda', 6, 3, 'VU', false),
  Ameacada(428, 'Hyalella caeca', 'Hyalellidae', 'Amphipoda', 6, 3, 'VU', false),
  Ameacada(429, 'Hyalella epikarstica', 'Hyalellidae', 'Amphipoda', 6, 3, 'CR', false),
  Ameacada(430, 'Hyalella formosa', 'Hyalellidae', 'Amphipoda', 6, 3, 'CR', false),
  Ameacada(431, 'Hyalella imbya', 'Hyalellidae', 'Amphipoda', 6, 3, 'CR', false),
  Ameacada(432, 'Hyalella veredae', 'Hyalellidae', 'Amphipoda', 6, 3, 'VU', false),
  Ameacada(433, 'Potiberaba porakuara', 'Mesogammaridae', 'Amphipoda', 6, 3, 'VU', false),
  Ameacada(434, 'Seborgia potiguar', 'Seborgiidae', 'Amphipoda', 6, 3, 'CR', false),
  Ameacada(435, 'Aegla brevipalma', 'Aeglidae', 'Decapoda', 6, 3, 'CR', false, 'Caranguejo-de-rio, egla'),
  Ameacada(436, 'Aegla camargoi', 'Aeglidae', 'Decapoda', 6, 3, 'EN', false, 'Caranguejo-de-rio, egla'),
  Ameacada(437, 'Aegla cavernicola', 'Aeglidae', 'Decapoda', 6, 3, 'CR', false, 'Caranguejo-de-rio, egla'),
  Ameacada(438, 'Aegla charon', 'Aeglidae', 'Decapoda', 6, 3, 'CR', false),
  Ameacada(439, 'Aegla franca', 'Aeglidae', 'Decapoda', 6, 3, 'EN', false, 'Caranguejo-de-rio, egla'),
  Ameacada(440, 'Aegla georginae', 'Aeglidae', 'Decapoda', 6, 3, 'EN', true),
  Ameacada(441, 'Aegla inconspicua', 'Aeglidae', 'Decapoda', 6, 3, 'VU', false, 'Caranguejo-de-rio, egla'),
  Ameacada(442, 'Aegla inermis', 'Aeglidae', 'Decapoda', 6, 3, 'EN', false, 'Caranguejo-de-rio, egla'),
  Ameacada(443, 'Aegla itacolomiensis', 'Aeglidae', 'Decapoda', 6, 3, 'EN', false, 'Caranguejo-de-rio, egla'),
  Ameacada(444, 'Aegla leachi', 'Aeglidae', 'Decapoda', 6, 3, 'EN', false, 'Caranguejo-de-rio, egla'),
  Ameacada(445, 'Aegla leptochela', 'Aeglidae', 'Decapoda', 6, 3, 'CR', false, 'Caranguejo-de-rio, egla'),
  Ameacada(446, 'Aegla loyolai', 'Aeglidae', 'Decapoda', 6, 3, 'EN', true),
  Ameacada(447, 'Aegla ludwigi', 'Aeglidae', 'Decapoda', 6, 3, 'EN', true),
  Ameacada(448, 'Aegla manuinflata', 'Aeglidae', 'Decapoda', 6, 3, 'EN', false, 'Caranguejo-de-rio, egla'),
  Ameacada(449, 'Aegla meloi', 'Aeglidae', 'Decapoda', 6, 3, 'EN', true),
  Ameacada(450, 'Aegla microphthalma', 'Aeglidae', 'Decapoda', 6, 3, 'CR', false),
  Ameacada(451, 'Aegla oblata', 'Aeglidae', 'Decapoda', 6, 3, 'EN', false, 'Caranguejo-de-rio, egla'),
  Ameacada(452, 'Aegla obstipa', 'Aeglidae', 'Decapoda', 6, 3, 'EN', false, 'Caranguejo-de-rio, egla'),
  Ameacada(453, 'Aegla okora', 'Aeglidae', 'Decapoda', 6, 3, 'EN', true),
  Ameacada(454, 'Aegla perobae', 'Aeglidae', 'Decapoda', 6, 3, 'EN', false, 'Caranguejo-de-rio, egla'),
  Ameacada(455, 'Aegla renana', 'Aeglidae', 'Decapoda', 6, 3, 'EN', false, 'Caranguejo-de-rio, egla'),
  Ameacada(456, 'Aegla rosanae', 'Aeglidae', 'Decapoda', 6, 3, 'EN', true),
  Ameacada(457, 'Aegla violacea', 'Aeglidae', 'Decapoda', 6, 3, 'EN', false, 'Caranguejo-de-rio, egla'),
  Ameacada(458, 'Macrobrachium denticulatum', 'Palaemonidae', 'Decapoda', 6, 3, 'VU', true),
  Ameacada(459, 'Parastacus tuerkayi', 'Parastacidae', 'Decapoda', 6, 3, 'EN', true),
  Ameacada(460, 'Kingsleya attenboroughi', 'Pseudothelphusidae', 'Decapoda', 6, 3, 'EN', true),
  Ameacada(461, 'Brasileirinho cavaticus', 'Brasileirinidae', 'Isopoda', 6, 3, 'CR', false),
  Ameacada(462, 'Pongycarcinia xiphidiourus', 'Calabozoidae', 'Isopoda', 6, 3, 'EN', false),
  Ameacada(463, 'Girardia arenicola', 'Dugesiidae', 'Tricladida', 7, 3, 'CR', false),
  Ameacada(464, 'Girardia desiderensis', 'Dugesiidae', 'Tricladida', 7, 3, 'CR', false),
  Ameacada(465, 'Girardia multidiverticulata', 'Dugesiidae', 'Tricladida', 7, 3, 'CR', false),
  Ameacada(466, 'Girardia paucipunctata', 'Dugesiidae', 'Tricladida', 7, 3, 'CR', false),
  Ameacada(467, 'Girardia spelaea', 'Dugesiidae', 'Tricladida', 7, 3, 'VU', false),
  Ameacada(468, 'Sluysia triapertura', 'Uteriporidae', 'Tricladida', 7, 3, 'CR', false),
  Ameacada(469, 'Hausera hauseri', 'Dimarcusidae', 'Tricladida', 7, 3, 'VU', false),
  Ameacada(470, 'Condylactis gigantea', 'Actiniidae', 'Actiniaria', 8, 4, 'VU', false, 'Anêmona-gigante'),
  Ameacada(471, 'Plexaurella obesa', 'Plexauridae', 'Alcyonacea', 8, 4, 'CR', true),
  Ameacada(472, 'Mussismilia braziliensis', 'Faviidae', 'Scleractinia', 8, 4, 'VU', false, 'Coral-cérebro-da-bahia'),
  Ameacada(473, 'Mussismilia harttii', 'Faviidae', 'Scleractinia', 8, 4, 'EN', false, 'Coral-vela'),
  Ameacada(474, 'Astropecten marginatus', 'Astropectinidae', 'Paxillosida', 9, 4, 'VU', false, 'Estrela-do-mar'),
  Ameacada(475, 'Linckia guildingi', 'Ophidiasteridae', 'Valvatida', 9, 4, 'VU', false, 'Estrela-do-mar'),
  Ameacada(476, 'Oreaster reticulatus', 'Oreasteridae', 'Valvatida', 9, 4, 'VU', false, 'Estrela-do-mar'),
  Ameacada(477, 'Euvola ziczac', 'Pectinidae', 'Pectinida', 2, 4, 'EN', false, 'Vieira'),
  Ameacada(478, 'Cassidulus infidus', 'Cassidulidae', 'Cassiduloida', 10, 4, 'EN', true),
  Ameacada(479, 'Cassidulus mitis', 'Cassidulidae', 'Cassiduloida', 10, 4, 'VU', false, 'Ouriço-do-mar'),
  Ameacada(480, 'Cassis tuberosa', 'Cassidae', 'Littorinimorpha', 4, 4, 'VU', true),
  Ameacada(481, 'Eustrombus goliath', 'Strombidae', 'Littorinimorpha', 4, 4, 'EN', false, 'Búzio-de-chapeu'),
  Ameacada(482, 'Macrostrombus costatus', 'Strombidae', 'Littorinimorpha', 4, 4, 'VU', false),
  Ameacada(483, 'Petaloconchus myrakeenae', 'Vermetidae', 'Littorinimorpha', 4, 4, 'VU', false),
  Ameacada(484, 'Synaptula secreta', 'Synaptidae', 'Apodida', 11, 4, 'CR', false, 'Pepino-do-mar'),
  Ameacada(485, 'Parathyone surinamensis', 'Cucumariidae', 'Dendrochirotida', 11, 4, 'VU', true),
  Ameacada(486, 'Millepora braziliensis', 'Milleporidae', 'Anthoathecata', 12, 4, 'CR', true),
  Ameacada(487, 'Millepora laboreli', 'Milleporidae', 'Anthoathecata', 12, 4, 'VU', false),
  Ameacada(488, 'Cardisoma guanhumi', 'Gecarcinidae', 'Decapoda', 6, 4, 'VU', false, 'Guaiamum'),
  Ameacada(489, 'Johngarthia lagostoma', 'Gecarcinidae', 'Decapoda', 6, 4, 'EN', false, 'Caranguejo-amarelo'),
  Ameacada(490, 'Diopatra victoriae', 'Onuphidae', 'Eunicida', 13, 4, 'EN', true),
];

/// Quantas espécies a Lista traz em cada categoria de risco.
int quantasNaCategoria(String cat) =>
    listaAmeacadas.where((a) => a.cat == cat).length;

/// Quantas espécies a Lista traz em cada grupo taxonômico.
int quantasNoGrupo(int grupo) =>
    listaAmeacadas.where((a) => a.grupo == grupo).length;

