// =====================================================================
// OS NOMES QUE AS PESSOAS USAM
//
// Portaria MPA nº 532, de 23 de setembro de 2025 — nomes científicos e
// respectivos nomes comuns das principais espécies de peixes de
// interesse comercial. DOU de 24/09/2025, edição 182, página 68.
//
// Por que esta tabela existe: quem consulta este aplicativo diz
// "carapeba", não "Diapterus rhombeus". Sem a tradução, a busca não
// encontra, e uma busca que não encontra parece dizer que não há regra.
//
// O art. 5º da Portaria 532 revogou a IN MAPA nº 53, de 1º de setembro
// de 2020, e a Portaria MAPA nº 570, de 23 de março de 2023, que
// tratavam do mesmo assunto. Esta é a tabela em vigor.
//
// ATENÇÃO AO QUE ESTA TABELA É E AO QUE NÃO É. Ela vale para ROTULAGEM
// de produtos destinados ao comércio nacional (art. 2º). Não cria nem
// afasta regra de pesca: o próprio art. 4º diz que ela "não exclui a
// obrigatoriedade de observar os regramentos estabelecidos em normas de
// ordenamento e nas demais restrições vigentes". Aqui ela serve para
// uma coisa só: traduzir o nome falado no nome que as normas escrevem.
//
// 571 espécies, 861 nomes comuns distintos.
// =====================================================================

/// Nome científico -> nomes comuns oficiais.
const nomesOficiais = <String, List<String>>{
  'Acanthistius brasilianus': ['Garoupa', 'Garoupa-Senhor-de-Engenho'],
  'Acanthocybium solandri': ['Cavala', 'Cavala-Empinge', 'Cavala-Aipim'],
  'Acanthurus bahianus': ['Caraúna'],
  'Acanthurus chirurgus': ['Caraúna'],
  'Acanthurus coeruleus': ['Caraúna'],
  'Acestrorhynchus falcirostris': ['Cachorro', 'cachorrinho', 'dente de cachorro', 'dente de cão', 'uéua'],
  'Acipenser baerii': ['Esturjão', 'Esturjão Siberiano'],
  'Acipenser gueldenstaedtii': ['Esturjão', 'Esturjão Russo'],
  'Acipenser medirostris': ['Esturjão', 'Esturjão Verde'],
  'Acipenser naccarii': ['Esturjão', 'Esturjão Adriático'],
  'Acipenser nudiventris': ['Esturjão', 'Esturjão Espinhoso'],
  'Acipenser oxyrinchus': ['Esturjão', 'Esturjão do Golfo', 'Esturjão do Atlântico'],
  'Acipenser sinensis': ['Esturjão', 'Esturjão Chinês'],
  'Acipenser spp.': ['Esturjão'],
  'Acipenser stellatus': ['Esturjão', 'Esturjão Estrela', 'Esturjão Strellatus'],
  'Acipenser sturio': ['Esturjão', 'Esturjão Europeu', 'Esturjão Báltico'],
  'Acipenser transmontanus': ['Esturjão', 'Esturjão Branco'],
  'Aetobatus narinari': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Pintada', 'Raia-Pintada'],
  'Ageneiosus inermis': ['Mandubé', 'Fidalgo', 'Palmito'],
  'Alectis ciliaris': ['Peixe-Galo', 'Peixe-Galo-do-Alto', 'Xaréu-Branco', 'Aracanguira'],
  'Alepocephalus bairdii': ['Celindra'],
  'Alerus spp.': ['Cangulo'],
  'Alopias superciliosus': ['Cação', 'Tubarão', 'Cação-Raposa', 'Tubarão-Raposa'],
  'Alopias vulpinus': ['Cação', 'Tubarão', 'Cação-Raposa', 'Tubarão-Raposa'],
  'Alosa fallax': ['Savelha'],
  'Aluterus spp.': ['Cangulo', 'Peixe-Porco', 'Peroá', 'Porquinho'],
  'Anarhichas denticulatus': ['Peixe-Lobo-Azul'],
  'Anchoa spp.': ['Manjuba'],
  'Anchoviella lepidentostole': ['Manjuba'],
  'Anguilla anguilla': ['Enguia', 'Enguia-Europeia'],
  'Anguilla japonica': ['Enguia', 'Enguia-Japonesa', 'Unagi', 'Unagui'],
  'Anguilla spp.': ['Enguia'],
  'Anisotremus surinamensis': ['Sargo', 'Sargo-de-Beiço', 'Pirambú'],
  'Anisotremus virginicus': ['Salema', 'Mercador'],
  'Anodus elongatus': ['Cubiu'],
  'Anoplopoma fimbria': ['Peixe-Carvão-do-Pacifico', 'Gindara'],
  'Aphanopus carbo': ['Peixe-Espada-Preto', 'Peixe-Espada-Negro'],
  'Arapaima gigas': ['Pirarucu'],
  'Archosargus probatocephalus': ['Sargo', 'Sargo-de-Dente'],
  'Archosargus rhomboidalis': ['Sargo', 'Sargo-de-Dente'],
  'Arctogadus glacialis': ['Bacalhau-do-Ártico'],
  'Argentina silus': ['Argentina-Dourada', 'Dourada-Argentina'],
  'Argyrosomus regius': ['Peixe-Sombra-do-Atlântico'],
  'Arius spp.': ['Bagre'],
  'Astronotus ocellatus': ['Apaiari', 'Acará-Açu', 'Cará-Açu'],
  'Astroscopus sexspinosus': ['Miracéu'],
  'Astyanax spp.': ['Lambari'],
  'Atheresthes stomias': ['Alabote-Dente-Curvo', 'Alabote-Flecha', 'Alabote-Dente-de-Flecha'],
  'Atherina boyeri': ['Peixe-Rei-do-Mediterrâneo'],
  'Atherinella brasiliensis': ['Peixe-Rei'],
  'Atlantoraja castelnaui': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Chita', 'Raia-Chita'],
  'Atlantoraja cyclophora': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Carimbada', 'Raia-Carimbada'],
  'Atlantoraja spp.': ['Arraia', 'Raia', 'Emplastro'],
  'Austroglossus microlepis': ['Solha-Austral'],
  'Auxis thazard': ['Bonito', 'Bonito-Cachorro'],
  'Bagre bagre': ['Bagre', 'Bagre-de-Penacho', 'Bagre-Bandeirado', 'Bandeirado'],
  'Bagre marinus': ['Bagre', 'Bagre-de-Fita'],
  'Bagre spp.': ['Bagre'],
  'Balistes spp.': ['Peixe-Porco', 'Porquinho', 'Peroá', 'Cangulo'],
  'Bathyraja spinicauda': ['Arraia', 'Raia', 'Emplastro', 'Arraia-da-Groelância', 'Raia-da-Groelândia'],
  'Bathyraja spp.': ['Arraia', 'Raia', 'Emplastro'],
  'Bathytoshia centroura': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Prego-Lixa', 'Raia-Prego-Lixa'],
  'Beryx splendens': ['Peixe-Imperador-de-Costa-Estreita Boreogadus saída Bacalhau-Polar'],
  'Boridia grossidens': ['Cocoroca'],
  'Brachygenys chrysargyrea': ['Xira-Amarela', 'Cocoroca-Boquinha'],
  'Brachyplatystoma filamentosum': ['Filhote', 'Piraíba'],
  'Brachyplatystoma flavicans': ['Dourada'],
  'Brachyplatystoma juruense': ['Dourada-Zebra'],
  'Brachyplatystoma platynema': ['Bagre', 'Babão'],
  'Brachyplatystoma platynemum': ['Barbado'],
  'Brachyplatystoma rousseauxii': ['Dourada'],
  'Brachyplatystoma tigrinum': ['Zebra', 'Zebrinha'],
  'Brachyplatystoma vaillantii': ['Piramutaba'],
  'Brama australis': ['Xaputa', 'Reineta'],
  'Brama spp.': ['Xaputa'],
  'Breviraja spinosa': ['Arraia', 'Raia', 'Emplastro'],
  'Brevoortia spp.': ['Savelha'],
  'Brosme brosme': ['Brosme', 'Brosmio', 'Zarbo'],
  'Brotula spp.': ['Brótula'],
  'Brycon amazonicus': ['Matrinxã'],
  'Brycon gouldingi': ['Piabanha'],
  'Brycon hilarii': ['Piraputanga'],
  'Brycon melanopterus': ['Jatuarana'],
  'Brycon orbignyanus': ['Piracanjuba'],
  'Brycon orthotaenia': ['Matrinxã-do-São-Francisco'],
  'Brycon spp.': ['Matrinxã'],
  'Calamus spp.': ['Peixe-Pena'],
  'Callichthys spp.': ['Tamboatá', 'Tamoatá', 'Tamuatá', 'Cascudo'],
  'Callorhinchus callorhynchus': ['Peixe-Elefante'],
  'Calophysus macropterus': ['Piracatinga', 'Urubu-d\'água', 'Douradinha'],
  'Caranx bartholomaei': ['Xaréu', 'Xarelete', 'Xerelete', 'Carapau', 'Xaréu-Amarelo', 'Xerelete-Amarelo', 'Xarelete-Amarelo'],
  'Caranx crysos': ['Xaréu', 'Xarelete', 'Xerelete', 'Carapau', 'Garajuba'],
  'Caranx hippos': ['Xaréu', 'Xarelete', 'Xerelete', 'Carapau', 'Xaréu-Cabeçudo', 'Xerelete-Cabeçudo', 'Xarelete-Cabeçudo'],
  'Caranx latus': ['Xaréu', 'Xarelete', 'Xerelete', 'Carapau', 'Xaréu-Olhudo', 'Xerelete-Olhudo', 'Xarelete-Olhudo', 'Garacimbora'],
  'Caranx lugubris': ['Xaréu', 'Xarelete', 'Xerelete', 'Carapau', 'Xaréu-Preto', 'Xarelete-Preto', 'Xerelete-Preto'],
  'Caranx ruber': ['Xaréu', 'Xarelete', 'Xerelete', 'Carapau', 'Xaréu-Azul', 'Xerelete-Azul', 'Xarelete-Azul'],
  'Caranx spp.': ['Xaréu', 'Xarelete', 'Xerelete', 'Carapau'],
  'Carcharhinus falciformis': ['Cação', 'Tubarão', 'Cação Lombo-Preto', 'Tubarão Lombo-Preto'],
  'Carcharhinus signatus': ['Cação', 'Tubarão', 'Cação-Noturno', 'Tubarão-Noturno'],
  'Carcharhinus spp.': ['Cação', 'Tubarão'],
  'Carcharias taurus': ['Cação', 'Tubarão', 'Cação-Mangona', 'Tubarão-Mangona'],
  'Carcharodon carcharias': ['Cação', 'Tubarão', 'Tubarão Branco'],
  'Cathorops spixii': ['Bagre', 'Bagre-Amarelo', 'Bagre-Uricica', 'Uricica'],
  'Caulolatilus chrysops': ['Batata', 'Batata-de-Pedra'],
  'Centropomus parallelus': ['Robalo', 'Robalo-Peva', 'Camurim', 'Camorim'],
  'Centropomus spp.': ['Robalo', 'Camurim', 'Camorim'],
  'Centropomus undecimalis': ['Robalo', 'Robalo-Flecha', 'Camurim', 'Camorim'],
  'Cephalopholis fulva': ['Piraúna', 'Catuá'],
  'Cetengraulis edentulus': ['Biqueirão', 'Biqueirão-do-Rabo-Amarelo', 'Manjuba-Boca-Torta', 'Boca-Torta'],
  'Cetengraulis mysticetus': ['Biqueirão', 'Biqueirão-do-Pacífico-Central'],
  'Cetorhinus maximus': ['Cação', 'Tubarão', 'Cação-Peregrino', 'Tubarão-Peregrino'],
  'Chaetodipterus faber': ['Paru', 'Paru-Branco', 'Enchada'],
  'Chalceus erythrurus': ['Arari'],
  'Cheilopogon cyanopterus': ['Peixe-Voador', 'Peixe-Voador-Holandês'],
  'Cheilopogon heterurus': ['Peixe-Voador'],
  'Chelon labrosus': ['Tainha', 'Tainhota'],
  'Chloroscombrus chrysurus': ['Palombeta'],
  'Cichla spp.': ['Tucunaré'],
  'Cichlasoma spp.': ['Acará', 'Cará Cilus Gilberti Corvina-Pampera'],
  'Clarias gariepinus': ['Bagre-africano'],
  'Clupea harengus': ['Arenque'],
  'Clupea pallasii': ['Arenque-do-Pacífico Cololabis Saira Sauri-do-Pacífico', 'Sauro-do-Pacífico'],
  'Colossoma macropomum': ['Tambaqui'],
  'Conger spp.': ['Congro'],
  'Conodon nobilis': ['Roncador', 'Coró', 'Coró-Roncador'],
  'Coryphaena equiselis': ['Dourado', 'Dourado-do-Mar', 'Mahi-Mahi'],
  'Coryphaena hippurus': ['Dourado', 'Dourado-do-Mar', 'Mahi-Mahi'],
  'Coryphaenoides rupestris': ['Peixe-Lagartixa-da-Rocha'],
  'Crenicichla spp.': ['Jacundá'],
  'Ctenopharyngodon idella': ['Carpa-Capim'],
  'Cyclopterus lumpus': ['Peixe-Lapa'],
  'Cynoscion acoupa': ['Pescada', 'Pescada-Amarela', 'Pescada-Jaguara'],
  'Cynoscion guatucupa': ['Pescada', 'Pescada-Olhuda', 'Pescada-Maria-Mole'],
  'Cynoscion jamaicensis': ['Pescada', 'Goete', 'Pescada-Goete'],
  'Cynoscion leiarchus': ['Pescada', 'Pescada-Branca'],
  'Cynoscion microlepidotus': ['Pescada', 'Pescada-Dentão', 'Pescada-Bicuda'],
  'Cynoscion spp.': ['Pescada'],
  'Cynoscion steindachneri': ['Pescada', 'Pescada-Verdadeira'],
  'Cynoscion virescens': ['Pescada', 'Pescada-Cambucu', 'Pescada-Cambuçu', 'Pescada-Cambuci', 'Pescada-Corvina'],
  'Cyphocharax voga': ['Birú', 'Voga', 'Peixe Voga'],
  'Cyprinus carpio': ['Carpa-Comum'],
  'Dasyatis hypostigma': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Mijona- Raia-Mijona'],
  'Dasyatis spp.': ['Arraia', 'Raia', 'Emplastro'],
  'Decapterus spp.': ['Charro'],
  'Dentex spp.': ['Dentão'],
  'Dermatolepis inermis': ['Garoupa', 'Garoupa-Gostosa'],
  'Diapterus auratus': ['Carapeba'],
  'Diapterus rhombeus': ['Carapeba'],
  'Dicentrarchus labrax': ['Lubina', 'Robalete', 'Robalo-Europeu'],
  'Diplodus spp.': ['Sargo', 'Sargo-Marimbá', 'Sargo-Marimbau', 'Marimbá', 'Marimbau', 'Pargo-Branco'],
  'Dissostichus eleginoides': ['Marlonga', 'Marlonga-Negra', 'Merluza-Negra'],
  'Dissostichus mawsoni': ['Marlonga', 'Marlonga-do-Antártico', 'Merluza-Antártica'],
  'Dissostichus spp.': ['Marlonga'],
  'Elagatis bipinnulata': ['Olhete', 'Arabaiana', 'Olhete-do-Norte', 'Arabaiana-do-Norte', 'Olhete Azul', 'Arabaiana-Azul Olhete-Rei', 'Arabaiana-Rei', 'Olhete-Arco-Íris', 'Arabaiana-Arco-Íris'],
  'Eleginops maclovinus': ['Babosa-da-Patagônia'],
  'Eleginus gracilis': ['Bacalhau-do-Ártico'],
  'Elops saurus': ['Ubarana', 'Albarana'],
  'Engraulis anchoita': ['Biqueirão-Argentino', 'Anchoíta'],
  'Engraulis encrasicolus': ['Biqueirão'],
  'Engraulis japonicus': ['Biqueirão-do-Indo-Pacífico', 'Biqueirão-Japonês'],
  'Engraulis mordax': ['Biqueirão-do-Pacífico-Norte'],
  'Engraulis ringens': ['Biqueirão-do-Perú', 'Anchoveta'],
  'Eopsetta jordani': ['Solha', 'Solha-da-Califórnia'],
  'Epigonus telescopus': ['Olhudo'],
  'Epinephelus adscensionis': ['Garoupa', 'Garoupa-Gato', 'Garoupa-Pintada'],
  'Epinephelus guttatus': ['Garoupa', 'Garoupa-Pintada'],
  'Epinephelus itajara': ['Mero'],
  'Epinephelus marginatus': ['Garoupa', 'Garoupa-Verdadeira'],
  'Epinephelus morio': ['Garoupa', 'Garoupa-Vermelha', 'Garoupa-de-São-Tomé', 'Garoupa-Vermelha-de-Abrolhos'],
  'Epinephelus striatus': ['Garoupa', 'Garoupa-de-Trindade'],
  'Etelis oculatus': ['Olhão', 'Vermelho-Olhão', 'Olho-de-Vidro'],
  'Etrumeus spp.': ['Arenque-Redondo'],
  'Eugerres brasilianus': ['Carapeba-Listrada'],
  'Euthynnus alletteratus': ['Bonito', 'Bonito-Pintado'],
  'Exocoetus volitans': ['Peixe-Voador', 'Coió'],
  'Fistularia petimba': ['Peixe-Corneta', 'Peixe-Trombeta'],
  'Fistularia tabacaria': ['Peixe-Corneta', 'Peixe-Trombeta'],
  'Gadus chalcogrammus': ['Polaca-do-Alasca'],
  'Gadus macrocephalus': ['Bacalhau', 'Bacalhau-do-Pacífico', 'Cod-do-Pacífico'],
  'Gadus morhua': ['Bacalhau', 'Bacalhau-do-Porto', 'Bacalhau-do-Atlântico', 'Cod', 'Cod-do-Atlântico', 'Morhua'],
  'Gadus ogac': ['Bacalhau', 'Bacalhau-da-Groenlândia'],
  'Galeocerdo cuvier': ['Cação', 'Tubarão', 'Cação-Tintureiro', 'Tubarão-Tintureiro', 'Cação-Tigre', 'Tubarão-Tigre'],
  'Galeorhinus galeus': ['Cação', 'Tubarão', 'Cação-Bico-Doce', 'Tubarão-Bico-Doce'],
  'Gasterochisma melampus': ['Peixe-Serra-Borboleta'],
  'Genidens barbus': ['Bagre', 'Bagre-Rosado'],
  'Genidens genidens': ['Bagre', 'Bagre-Rosado'],
  'Genidens planifrons': ['Bagre'],
  'Genidens spp.': ['Bagre'],
  'Genyatremus luteus': ['Coró', 'Peixe-Pedra', 'Golosa'],
  'Genypterus blacodes': ['Congro', 'Abadejo', 'Congro-Rosa'],
  'Genypterus brasiliensis': ['Congro', 'Abadejo', 'Congro-Rosa'],
  'Genypterus chilensis': ['Congro', 'Abadejo', 'Congro-Vermelho'],
  'Genypterus maculatus': ['Congro', 'Abadejo', 'Congro-Negro'],
  'Genypterus spp.': ['Congro', 'Abadejo'],
  'Geophagus spp.': ['Acará', 'Cará'],
  'Ginglymostoma cirratum': ['Cação', 'Tubarão', 'Cação-Lixa', 'Tubarão-Lixa', 'Tubarão- Enfermeiro', 'Tubarão-Pajem', 'Cação-Lambaru', 'Tubarão-Lambaru'],
  'Glyptocephalus cynoglossus': ['Solhão'],
  'Glyptocephalus zachirus': ['Solhão-Americano'],
  'Gymnothorax spp.': ['Moréia', 'Enguia'],
  'Gymnura altavela': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Manteiga', 'Raia-Manteiga'],
  'Gymnura hirundo': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Borboleta', 'Raia-Borboleta'],
  'Gymnura micrura': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Borboleta-Lisa', 'Raia-Borboleta-Lisa'],
  'Haemulon album': ['Cocoroca-Branca'],
  'Haemulon aurolineatum': ['Xira-Branca', 'Sapuruna', 'Cotinga'],
  'Haemulon bonariense': ['Cocoroca-Negra'],
  'Haemulon carbonarium': ['Xira'],
  'Haemulon flavolineatum': ['Cambuba'],
  'Haemulon macrostoma': ['Xirão', 'Cocoroca-Espanhola'],
  'Haemulon melanurum': ['Sapuruna-de-Listra'],
  'Haemulon parra': ['Cambuba', 'Xira', 'Biquara'],
  'Haemulon plumierii': ['Biquara'],
  'Haemulon sciurus': ['Cocoroca-Boca-de-Fogo'],
  'Haemulon spp.': ['Cocoroca', 'Xira', 'Cambuba', 'Sapuruna', 'Biquara'],
  'Haemulon squamipinna': ['Xira-Amarela'],
  'Haemulon steindachneri': ['Cocoroca-Boca-Larga'],
  'Haemulon striatum': ['Cocoroca-Listrada'],
  'Haemulopsis corvinaeformis': ['Coró-branco'],
  'Halichoeres spp.': ['Budião', 'Bodião'],
  'Harengula clupeola': ['Sardinha-Cascuda'],
  'Helicolenus dactylopterus': ['Sarrão'],
  'Helicolenus lahillei': ['Sarrão'],
  'Helicolenus spp.': ['Cantarilho-do-Sul'],
  'Hemiodus spp.': ['Orana', 'Jatuarana-Escama-Grossa', 'Piau-Escama-Fina', 'Piau-Voador'],
  'Hemiramphus spp.': ['Agulha', 'Agulhinha'],
  'Hemisorubim platyrhynchos': ['Braço-de-Moça', 'Jurupoca', 'Jeripoca', 'Liro'],
  'Hexanchus griseus': ['Cação', 'Tubarão', 'Cação-Bruxa', 'Tubarão-Bruxa'],
  'Hippoglossoides elassodon': ['Solha', 'Solha-Japonesa'],
  'Hippoglossoides platessoides': ['Solha', 'Solha-Americana'],
  'Hippoglossus hippoglossus': ['Alabote-do-Atlântico', 'Halibute', 'Halibute-do-Atlântico'],
  'Hippoglossus stenolepis': ['Alabote-do-Pacífico', 'Halibute', 'Halibute-do-Pacífico'],
  'Hirundichthys affinis': ['Peixe-Voador', 'Coió'],
  'Holacanthus ciliaris': ['Paru', 'Paru-Verde'],
  'Holocentrus adscensionis': ['Mariquita', 'Jaguariçá'],
  'Hoplerythrinus unitaeniatus': ['Jeju'],
  'Hoplias lacerdae': ['Traírão'],
  'Hoplias malabaricus': ['Traíra'],
  'Hoplosternum spp.': ['Tamuatá', 'Tamoatá', 'Tamboatá', 'Cascudo'],
  'Hoplostethus atlanticus': ['Olho-de-Vidro-Laranja'],
  'Huso dauricus': ['Esturjão-Kaluga'],
  'Huso huso': ['Esturjão-Beluga'],
  'Hypanus americanus': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Prego', 'Raia-Prego'],
  'Hypanus geijskesi': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Bicuda', 'Raia-Bicuda'],
  'Hypanus guttatus': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Lixa', 'Raia-Lixa'],
  'Hypanus say': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Amarela', 'Raia-Amarela'],
  'Hypophthalmichthys molitrix': ['Carpa-Prateada'],
  'Hypophthalmichthys nobilis': ['Carpa-Cabeça-Grande'],
  'Hypophthalmus edentatus': ['Mapará'],
  'Hypophthalmus fimbriatus': ['Mapará', 'Mapará-Bico-de-Pena'],
  'Hypophthalmus marginatus': ['Mapará'],
  'Hypophthalmus spp.': ['Mapará'],
  'Hyporhamphus spp.': ['Agulhinha', 'Agulha'],
  'Hyporthodus flavolimbatus': ['Cherne', 'Cherne-Amarelo'],
  'Hyporthodus mystacinus': ['Cherne', 'Cherne-Listrado'],
  'Hyporthodus nigritus': ['Cherne', 'Cherne-Queimado'],
  'Hyporthodus niveatus': ['Cherne', 'Cherne-Verdadeiro', 'Cherne-Pintado'],
  'Hypostomus spp.': ['Cascudo', 'Acari'],
  'Ictalurus punctatus': ['Catfish-Americano', 'Bagre-do-Canal'],
  'Ilisha amazonica': ['Sarda', 'Apapá'],
  'Isogomphodon oxyrhynchus': ['Cação', 'Tubarão', 'Cação-Bicudo', 'Tubarão-Bicudo', 'Cação-Espátula', 'Tubarão-Espátula', 'Cação-Quati', 'Tubarão-Quati'],
  'Istiompax indica': ['Marlim-preto'],
  'Istiophorus albicans': ['Agulhão-Vela', 'Agulhão-Bandeira'],
  'Isurus oxyrinchus': ['Cação', 'Tubarão', 'Cação-Anequim', 'Tubarão-Anequim', 'Cação-Mako', 'Tubarão-Mako'],
  'Isurus paucus': ['Cação', 'Tubarão', 'Cação-Anequim-Preto', 'Tubarão-Anequim-Preto', 'Cação-Mako-Preto', 'Tubarão-Mako-Preto'],
  'Kajikia albida': ['Agulhão-Branco', 'Agulhão-Prata', 'Marlim-Branco'],
  'Kajikia audax': ['Agulhão-Branco', 'Agulhão-Prata', 'Agulhão-Listrado', 'Marlim-Branco', 'Marlim-Listrado'],
  'Katsuwonus pelamis': ['Bonito-Listrado', 'Bonito-Barriga-Listrada', 'Gaiado', '(Atum*) * Apenas na previsão da Instrução Normativa SDA n', 'de 15/dez/2011'],
  'Kyphosus incisor': ['Piranjica', 'Pijirica', 'Pirajica'],
  'Lamna nasus': ['Cação', 'Tubarão', 'Cação-Moka', 'Tubarão-Moka', 'Cação-Sardo', 'Tubarão-Sardo'],
  'Lampris spp.': ['Peixe Cravo'],
  'Larimus breviceps': ['Oveva', 'Boca-Mole'],
  'Lates spp.': ['Perca-de-Água-Doce'],
  'Latris lineata': ['Peixe-Trompete-Listrado'],
  'Leiairius marmoratus': ['Pintado da Amazônia Piaractus mesopotamicus x', 'Pintado da Amazônia', 'Jundiara Pseudoplatystoma corruscans x'],
  'Leiarius marmoratus': ['Jundiá'],
  'Lepidocybium flavobrunneum': ['Peixe Prego', 'Escolar', 'Escolar-Preto'],
  'Lepidopsetta bilineata': ['Solha', 'Solha-da-Rocha'],
  'Lepidopus caudatus': ['Peixe-Espada-Branco'],
  'Leporinus spp.': ['Piau', 'Piava', 'Piauçu', 'Piavuçu', 'Piapara', 'Aracu'],
  'Lepturacanthus savala': ['Peixe-Espada'],
  'Limanda spp.': ['Solha'],
  'Liparis spp.': ['Peixe-Caracol'],
  'Lithodoras dorsalis': ['Bacu', 'Bacu-Pedra'],
  'Lobotes surinamensis': ['Prejereba', 'Xancarrona', 'Chancarana', 'Curuaçu'],
  'Lophius spp.': ['Peixe-Sapo', 'Tamboril'],
  'Lopholatilus villarii': ['Batata', 'Batata-do-Alto', 'Peixe-Batata'],
  'Loricariichthys spp.': ['Cascudo'],
  'Luciopimelodus pati': ['Pati'],
  'Lutjanus analis': ['Vermelho', 'Cioba', 'Siriúba ou Sirioba'],
  'Lutjanus apodus': ['Vermelho', 'Caranha', 'Caranha-Baúna'],
  'Lutjanus buccanella': ['Vermelho', 'Saçupema', 'Saçupema-Boca-Preta', 'Vermelho-de-Fundo'],
  'Lutjanus campechanus': ['Vermelho', 'Pargo'],
  'Lutjanus cyanopterus': ['Vermelho', 'Caranha', 'Caranha-de-Fundo'],
  'Lutjanus griseus': ['Vermelho', 'Caranha', 'Caranha-do-Mangue'],
  'Lutjanus jocu': ['Vermelho', 'Dentão'],
  'Lutjanus purpureus': ['Vermelho', 'Pargo', 'Pargo-Vermelho'],
  'Lutjanus spp.': ['Vermelho'],
  'Lutjanus synagris': ['Vermelho', 'Ariacó', 'Ariocó'],
  'Lutjanus vivanus': ['Vermelho', 'Dentão', 'Carapitanga', 'Vermelho-de-Olho-Amarelo', 'Pargo-do-Olho-Amarelo'],
  'Lycengraulis grossidens': ['Manjuba'],
  'Macrodon ancylodon': ['Pescadinha', 'Pescadinha-Real', 'Pescada-Gó', 'Pescada-Foguete'],
  'Macrourus spp.': ['Granadeiro', 'Granadero'],
  'Macruronus magellanicus': ['Merluza-de-Cauda'],
  'Macruronus novaezelandiae': ['Merluza-Granadeiro-Azul', 'Merluza-da-Nova-Zelandia'],
  'Makaira nigricans': ['Agulhão-Preto', 'Agulhão-Negro', 'Marlim-Azul'],
  'Malacanthus plumieri': ['Pirá'],
  'Mallotus villosus': ['Capelim'],
  'Masturus lanceolatus': ['Peixe-Lua'],
  'Megalops atlanticus': ['Tarpon', 'Tarpão', 'Camurupim', 'Pema', 'Pirapema'],
  'Melanogrammus aeglefinus': ['Lubina', 'Haddock'],
  'Menticirrhus spp.': ['Papa-Terra', 'Betara'],
  'Merluccius australis': ['Merluza', 'Merluza-Austral'],
  'Merluccius spp.': ['Merluza'],
  'Micromesistius australis': ['Polaca'],
  'Micromesistius poutassou': ['Verdinho'],
  'Micropogonias altipinnis': ['Corvina', 'Corvina-Dourada'],
  'Micropogonias furnieri': ['Corvina', 'Curuca', 'Cascote', 'Cururuca'],
  'Micropogonias undulatus': ['Corvina', 'Curuca', 'Cascote', 'Cururuca'],
  'Microstomus pacificus': ['Solha', 'Solha-de-Dover'],
  'Mobula birostris': ['Arraia', 'Raia', 'Arraia-Jamanta', 'Raia-Jamanta', 'Manta', 'Arraia-Manta', 'Raia-Manta'],
  'Mola mola': ['Peixe-Lua'],
  'Molva dypterygia': ['Ling-Azul'],
  'Molva molva': ['Ling'],
  'Monacanthus spp.': ['Cangulo', 'Peixe Porco', 'Peroá', 'Porquinho'],
  'Mora moro': ['Mora'],
  'Mugil capurrii': ['Tainha', 'Tainha Africana'],
  'Mugil cephalus': ['Tainha', 'Tainhota'],
  'Mugil curema': ['Parati', 'Saúna', 'Pratiqueira', 'Parati-Cara-Amarela'],
  'Mugil liza': ['Tainha', 'Tainhota'],
  'Mulloidichthys martinicus': ['Trilha-Amarela', 'Saramunete', 'Saramonete'],
  'Mullus argentinae': ['Trilha', 'Salmonete'],
  'Mustelus canis': ['Cação', 'Tubarão', 'Cação-Cachorro', 'Tubarão-Cachorro', 'Cação-Fiusa', 'Tubarão-Fiusa'],
  'Mustelus fasciatus': ['Cação', 'Tubarão', 'Cação-Malhado', 'Tubarão-Malhado'],
  'Mustelus schmitti': ['Cação', 'Tubarão', 'Cação-Cola-Fina', 'Tubarão-Cola-Fina'],
  'Mustelus spp.': ['Cação', 'Tubarão', 'Caçonete'],
  'Mycteroperca acutirostris': ['Badejo', 'Badejo-Mira'],
  'Mycteroperca bonaci': ['Badejo', 'Badejo-Quadrado'],
  'Mycteroperca interstitialis': ['Badejo', 'Badejo Amarelo', 'Badejo Mané nego', 'Mané nego'],
  'Mycteroperca microlepis': ['Badejo', 'Badejo-da-Areia'],
  'Mycteroperca phenax': ['Badejo', 'Badejo Amarelo'],
  'Mycteroperca spp.': ['Badejo', 'Sirigado', 'Serigado'],
  'Mycteroperca venenosa': ['Badejo', 'Badejo Pirajica', 'Badejo Ferro'],
  'Myliobatis freminvillei': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Touro', 'Raia-Touro'],
  'Myliobatis goodei': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Sapo', 'Raia-Sapo'],
  'Myripristis jacobus': ['Fogueira', 'Piranema', 'Soldado'],
  'Narcine brasiliensis': ['Arraia-Elétrica', 'Raia-Elétrica', 'Arraia-Treme-Treme', 'Raia-Treme-Treme'],
  'Nebris microps': ['Pescada-Banana'],
  'Negaprion brevirostris': ['Cação', 'Tubarão', 'Cação-Limão', 'Tubarão-Limão', 'Cação-Papa- Areia', 'Tubarão-Papa-Areia'],
  'Nemadactylus bergi': ['Peixe-Bicudo', 'Bicudo', 'Papa-Mosca'],
  'Nemadactylus macropterus': ['Peixe-Bobo-Taraki', 'Tarakihi'],
  'Nemadactylus monodactylus': ['Peixe-Bobo'],
  'Nemipterus spp.': ['Falso-Besugos'],
  'Notarius bonillai': ['Bagre', 'Bagre-Uricica'],
  'Notarius grandicassis': ['Bagre', 'Bagre-Branco', 'Bagre-Cambeba', 'Cambeba', 'Bagre-Cambéu', 'Cambéu', 'Bagre-Cambéua', 'Cambéua', 'Bagre-Cambeua', 'Cambeua'],
  'Notarius quadriscutis': ['Bagre', 'Bagre-Cangatá', 'Cangatá', 'Bagre-Cangatã', 'Cangatã'],
  'Notarius rugispinis': ['Bagre', 'Bagre-Jurupiranga', 'Jurupiranga'],
  'Notarius spp.': ['Bagre'],
  'Notorynchus spp.': ['Cação', 'Tubarão', 'Cação-Bruxa-Pintado', 'Tubarão-Bruxa-Pintado'],
  'Notothenia spp.': ['Nototenia'],
  'Ocyurus chrysurus': ['Vermelho', 'Guaiúba', 'Cioba'],
  'Odontesthes spp.': ['Peixe-Rei'],
  'Oligoplites spp.': ['Timbiro', 'Timbira', 'Tibiro', 'Guaivira'],
  'Oligosarcus spp.': ['Dentudo', 'Peixe-Cachorro'],
  'Oncorhynchus gorbuscha': ['Salmão', 'Salmão-Pink', 'Salmão-Rosa'],
  'Oncorhynchus keta': ['Salmão', 'Salmão-Chum', 'Salmão-Cão'],
  'Oncorhynchus kisutch': ['Salmão', 'Salmão-Coho', 'Salmão-Prateado'],
  'Oncorhynchus mykiss': ['Truta', 'Truta-Arco-Íris'],
  'Oncorhynchus nerka': ['Salmão', 'Salmão-Sockeye', 'Salmão-Vermelho'],
  'Oncorhynchus tshawytscha': ['Salmão', 'Salmão-King', 'Salmão-Real'],
  'Ophichthus spp.': ['Enguia'],
  'Ophiodon elongatus': ['Ling-Verde'],
  'Opisthonema libertate': ['Sardinha-Laje'],
  'Opisthonema medirastre': ['Sardinha-Laje'],
  'Opisthonema oglinum': ['Sardinha-Laje'],
  'Oreochromis niloticus': ['Tilápia', 'Tilápia-do-Nilo', 'Tilápia-Saint-Peter Pseudoplatystoma spp x'],
  'Orthopristis rubra': ['Cocoroca', 'Cocoroca-Jurumin'],
  'Osteoglossum bicirrhosum': ['Aruanã'],
  'Otolithoides biauritus': ['Corvina-Bronze', 'Corvina-de-Bronze'],
  'Oxydoras kneri': ['Armado'],
  'Oxydoras niger': ['Cuiú', 'Cuiú-Cuiú', 'Cujuba', 'Cujubim'],
  'Pagellus acarne': ['Besugo', 'Aligote'],
  'Pagellus bogaraveo': ['Besugo', 'Goraz'],
  'Pagellus spp.': ['Besugo'],
  'Pagrus caeruleostictus': ['Pargo-Rosa', 'Pargo-Ruço'],
  'Pagrus pagrus': ['Pargo-Rosa'],
  'Pangasius spp.': ['Panga', 'Pangasius'],
  'Paralabrax humeralis': ['Cabrilla'],
  'Paralichthys spp.': ['Linguado'],
  'Paralonchurus brasiliensis': ['Maria-Luiza'],
  'Paralonchurus peruanus': ['Maria-Luiza'],
  'Parapercis colias': ['Nedopa-da-Novazelândia'],
  'Parapimelodus valenciennis': ['Mandi'],
  'Paraplagusia bilineata': ['Solha', 'Solha-da-Rocha'],
  'Parona signata': ['Pampo', 'Parona', 'Viúva', 'Peixe Tábua'],
  'Parophrys vetulus': ['Solha', 'Solha-Inglesa'],
  'Patagonotothen ramsayi': ['Nototenia'],
  'Pellona castelnaeana': ['Apapá', 'Apapá-Amarelo'],
  'Pellona flavipinnis': ['Apapá', 'Apapá-Branco'],
  'Pellona harroweri': ['Sardinha-Mole', 'Sardinha-Isopor'],
  'Pelotretis flavilatus': ['Solha', 'Solha-Limão', 'Solha-Limão-da-Novazelândia'],
  'Peltorhamphus novaezeelandiae': ['Solha', 'Solha-Comum', 'Solha-Comum-da-Novazelândia'],
  'Peprilus paru': ['Gordinho', 'Canguiro'],
  'Percophis brasiliensis': ['Tira-Vira', 'Vira-Vira'],
  'Phractocephalus hemioliopterus': ['Pirarara', 'Surubim', 'Cachapira'],
  'Phycis blennoides': ['Abrótea-do-Alto'],
  'Piaractus brachypomus': ['Pirapitinga', 'Tambatinga Oreochromis aureus x Oreochromis mossambicus x Sarotherodon galilaeus x', 'Patinga Pseudoplatystoma reticulatum x'],
  'Piaractus mesopotamicus': ['Pacu', 'Pacu-Caranha', 'Tambacu Colossoma macropomum x'],
  'Pimelodella spp.': ['Mandi'],
  'Pimelodina flavipinnis': ['Mandi-Moela', 'Mandirá'],
  'Pimelodus spp.': ['Pintadinho', 'Mandi'],
  'Pinguipes spp.': ['Quatis'],
  'Pinirampus pirinampu': ['Piranambú'],
  'Plagioscion auratus': ['Pescada-Preta'],
  'Plagioscion squamosissimus': ['Pescada-Branca', 'Pescada-do-Piauí'],
  'Platichthys flesus': ['Solha', 'Solha-da-Pedra'],
  'Platichthys stellatus': ['Solha', 'Solha-Estrelada'],
  'Platydoras costatus': ['Bacu'],
  'Platynematichthys notatus': ['Cara-de-Gato'],
  'Plecostomus spp.': ['Cascudo', 'Acari'],
  'Plectorhinchus mediterraneus': ['Peixe-Pombo'],
  'Pleuronectes platessa': ['Solha'],
  'Pleuronectes quadrituberculatus': ['Solha', 'Solha-do-Alasca'],
  'Pogonias cromis': ['Miragaia', 'Miraguaia'],
  'Pollachius virens': ['Saithe'],
  'Polyprion americanus': ['Cherne-Poveiro'],
  'Polyprion oxygeneios': ['Cherne-da-Nova-Zelândia'],
  'Pomacanthus spp.': ['Parú', 'Parú-Preto', 'Frade'],
  'Pomadasys spp.': ['Cocoroca'],
  'Pomatomus saltatrix': ['Enchova', 'Anchova'],
  'Porichthys porosissimus': ['Cabosa', 'Mangangá'],
  'Potamorhina spp.': ['Branquinha'],
  'Potamotrygon spp.': ['Arraia', 'Raia', 'Arraia-de-Água-Doce'],
  'Priacanthus arenatus': ['Olho-de-Cão'],
  'Prionace glauca': ['Cação', 'Tubarão', 'Cação-Azul', 'Tubarão-Azul'],
  'Prionotus spp.': ['Cabrinha', 'Cabra', 'Peixe-Cabra', 'Cascudinho-do-Mar', 'Cascudo-do-Mar'],
  'Pristis pectinata': ['Peixe-Serra'],
  'Pristis perotteti': ['Peixe-Serra'],
  'Prochilodus spp.': ['Curimba', 'Curimbatá', 'Curimatã'],
  'Protonibea diacanthus': ['Corvina-Pintada'],
  'Psammobatis spp.': ['Arraia', 'Raia', 'Emplastro'],
  'Psenopsis anomala': ['Peixe-Leme-do-Pacífico'],
  'Pseudocyttus maculatus': ['Peixe-Galo-da-Novazelândia'],
  'Pseudopercis numida': ['Namorado'],
  'Pseudopercis semifasciata': ['Namorado'],
  'Pseudophycis bachus': ['Abrótea-da-Nova-Zelândia'],
  'Pseudoplatystoma corruscans': ['Surubim', 'Surubim-Pintado', 'Pintado', 'Cachapinta Pseudoplatystoma reticulatum x'],
  'Pseudoplatystoma fasciatum': ['Surubim', 'Surubim-Cachara', 'Cachara'],
  'Pseudoplatystoma punctifer': ['Surubim', 'Surubim-Cachara', 'Cachara'],
  'Pseudoplatystoma reticulatum': ['Surubim', 'Surubim-Cachara', 'Cachara', 'Pintachara Pseudoplatystoma reticulatum x'],
  'Pseudoplatystoma spp.': ['Surubim'],
  'Pseudoplatystoma tigrinum': ['Surubim', 'Surubim-tigre', 'Caparari'],
  'Pseudopleuronectes americanus': ['Solha', 'Solha-de-Inverno'],
  'Pseudoscaphirhynchus spp.': ['Falso-Esturjão-Nariz-de-Pá'],
  'Pseudotolithus typus': ['Rainha-Branca'],
  'Pseudupeneus maculatus': ['Saramonete'],
  'Pterodoras granulosus': ['Abotoado', 'Bacu'],
  'Pterygoplichthys pardalis': ['Acarí', 'Acarí-Bodó', 'Cascudo'],
  'Pygocentrus spp.': ['Piranha'],
  'Rachycentron canadum': ['Bejupirá', 'Bijupirá', 'Beijupirá'],
  'Raja spp.': ['Arraia', 'Raia', 'Emplastro'],
  'Rajella purpuriventralis': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Roxa', 'Raia-Roxa'],
  'Rajella spp.': ['Arraia', 'Raia', 'Emplastro'],
  'Reinhardtius hippoglossoides': ['Alabote-da-Groenlândia'],
  'Rhamdia spp.': ['Jundiá'],
  'Rhincodon typus': ['Tubarão-Baleia'],
  'Rhinecanthus spp.': ['Peixe-Porco', 'Porquinho', 'Peroá', 'Cangulo'],
  'Rhinobatos spp.': ['Viola', 'Arraia-Viola', 'Raia-Viola'],
  'Rhinoptera spp.': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Ticonha', 'Raia-Ticonha'],
  'Rhizoprionodon lalandii': ['Cação', 'Tubarão', 'Cação-Frango', 'Tubarão-Frango'],
  'Rhizoprionodon porosus': ['Cação', 'Tubarão', 'Cação-Frango', 'Tubarão-Frango'],
  'Rhizoprionodon terraenovae': ['Cação', 'Tubarão', 'Cação-Rabo-Seco', 'Tubarão-Rabo-Seco'],
  'Rhomboplites aurorubens': ['Vermelho', 'Piranga', 'Paramirim', 'Realito', 'Vermelhinho', 'Cioba'],
  'Rhombosolea plebeia': ['Solha', 'Solha-da-Areia', 'Solha-da-Areia-da-Novazelândia'],
  'Rhytiodus spp.': ['Aracu'],
  'Rioraja agassizii': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Santa-do-Rio', 'Raia-Santa-do-Rio'],
  'Ruvettus pretiosus': ['Peixe-Prego', 'Escolar'],
  'Salilota spp.': ['Brótula'],
  'Salminus brasiliensis': ['Dourado', 'Dourado-de-Água-Doce'],
  'Salminus franciscanus': ['Dourado', 'Dourado-do-São-Francisco'],
  'Salmo salar': ['Salmão', 'Salmão-do-Atlântico'],
  'Sarda chiliensis': ['Bonito', 'Bonito-do-Pacífico', 'Sarda'],
  'Sarda sarda': ['Bonito', 'Bonito-do-Atlântico', 'Sarda'],
  'Sardina pilchardus': ['Sardinha'],
  'Sardinella albella': ['Sardinha-Branca'],
  'Sardinella aurita': ['Sardinha'],
  'Sardinella brasiliensis': ['Sardinha', 'Sardinha Verdadeira'],
  'Sardinella gibbosa': ['Sardinha'],
  'Sardinella longiceps': ['Sardinha'],
  'Sardinella maderensis': ['Sardinha-da-Madeira'],
  'Sardinops melanostictus': ['Sardinha', 'Sardinha-do-Pacífico'],
  'Sardinops sagax': ['Sardinha', 'Sardinha-do-Pacífico'],
  'Scaphirhynchus spp.': ['Esturjão-Nariz-de-Pá'],
  'Scarus spp.': ['Budião', 'Bodião', 'Bico-Verde'],
  'Schizodon spp.': ['Aracu', 'Araçu'],
  'Sciades couma': ['Bagre', 'Bagre-Catinga', 'Bagre-Cuma'],
  'Sciades parkeri': ['Bagre', 'Bagre-Gurijuba', 'Gurijuba'],
  'Sciades proops': ['Bagre', 'Bagre-Uritinga', 'Uritinga', 'Bagre-Urutinga', 'Urutinga'],
  'Sciades spp.': ['Bagre'],
  'Scomber australasicus': ['Cavalinha', 'Cavalinha-Pintada'],
  'Scomber colias': ['Cavalinha'],
  'Scomber japonicus': ['Cavalinha'],
  'Scomber scombrus': ['Cavala', 'Cavala-do-Atlântico'],
  'Scomberomorus brasiliensis': ['Cavala', 'Serra', 'Sororoca'],
  'Scomberomorus cavalla': ['Cavala', 'Cavala-Verdadeira'],
  'Scomberomorus maculatus': ['Cavala', 'Cavala-Pintada', 'Serrinha'],
  'Scomberomorus regalis': ['Cavala', 'Cavala-Branca', 'Serra-Pininga'],
  'Scomberomorus spp.': ['Cavala'],
  'Scyliorhinus spp.': ['Pata-Roxa'],
  'Sebastes spp.': ['Cantarilho-do-Norte'],
  'Selar crumenophthalmus': ['Garapau', 'Carapau'],
  'Selene spp.': ['Peixe-Galo', 'Galo'],
  'Selene vomer': ['Peixe-Galo', 'Peixe-Galo-de-Penacho'],
  'Semaprochilodus spp.': ['Jaraqui'],
  'Seriola spp.': ['Olhete', 'Arabaiana', 'Olho-de-Boi'],
  'Seriolella spp.': ['Seriolela'],
  'Serrasalmus spp.': ['Piranha', 'Piranha Preta'],
  'Sorubim lima': ['Bico-de-Pato'],
  'Sparisoma spp.': ['Budião', 'Bodião'],
  'Sphyraena spp.': ['Barracuda', 'Bicuda'],
  'Sphyrna spp.': ['Cação', 'Tubarão', 'Cação-Martelo', 'Tubarão-Martelo', 'Cação-Cambeva', 'Tubarão-Cambeva'],
  'Sprattus fuegensis': ['Espadilha', 'Espadilha Chilena'],
  'Sprattus sprattus': ['Espadilha', 'Espadilha Europeia'],
  'Squalus acanthias': ['Cação', 'Cação-Bagre', 'Cação-Prego'],
  'Squalus blainville': ['Cação', 'Cação-Espinho', 'Cação Bagre-Galhudo'],
  'Squalus cubensis': ['Cação', 'Cação-Bagre'],
  'Squalus megalops': ['Cação', 'Cação Bagre-Chato'],
  'Squalus mitsukurii': ['Cação', 'Cação Bagre-de-Espinho'],
  'Squatina guggenheim': ['Cação-Anjo-Espinhoso'],
  'Squatina occulta': ['Cação-Anjo-Liso'],
  'Squatina spp.': ['Cação-Anjo'],
  'Stellifer spp.': ['Cabeçudo', 'Cangoá'],
  'Strangomera bentincki': ['Arenque; Arenque-Chileno; Sardinha'],
  'Stromateus brasiliensis': ['Pampo', 'Pampo-Pintado', 'Papa-Figo'],
  'Stromateus fiatola': ['Pampo', 'Pampo-Gordinho'],
  'Syacium micrurumm': ['Linguado', 'Linguado-do-Canal'],
  'Syacium papillosum': ['Linguado', 'Linguado-de-Areia'],
  'Syacium spp.': ['Linguado'],
  'Symphurus spp.': ['Peixe-Língua', 'Língua-de-Mulata'],
  'Sympterygia acuta': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Santa-Bicuda', 'Raia-Santa-Bicuda'],
  'Sympterygia bonapartii': ['Arraia', 'Raia', 'Emplastro', 'Arraia-Santa-Mármore', 'Raia-Santa-Mármore'],
  'Synbranchus marmoratus': ['Mussum', 'Muçum'],
  'Tachysurus spp.': ['Bagre'],
  'Tetrapturus belone': ['Agulhão-do-Mediterrâneo', 'Marlim-do-Mediterrâneo'],
  'Tetrapturus pfluegeri': ['Agulhão-Verde', 'Aspinosa Agulhão-Estilete'],
  'Thunnus alalunga': ['Atum', 'Albacora-Branca', 'Atum-Voador'],
  'Thunnus albacares': ['Atum', 'Albacora-de-Lage', 'Atum-Galha-Amarela'],
  'Thunnus atlanticus': ['Atum', 'Albacorinha'],
  'Thunnus maccoyii': ['Atum- Atum-Azul-do-Sul'],
  'Thunnus obesus': ['Atum', 'Albacora-Bandolim'],
  'Thunnus spp.': ['Atum'],
  'Thunnus thynnus': ['Atum', 'Atum-Azul', 'Albacora-Azul'],
  'Thunnus tonggol': ['Atum', 'Atum-Azul-do-Norte'],
  'Thyrsites atun': ['Senuca'],
  'Thyrsites lepidopodea': ['Cavalinha-do-Norte'],
  'Trachinotus goodei': ['Pampo', 'Canguira', 'Pampo-Listrado'],
  'Trachinotus marginatus': ['Pampo', 'Canguira', 'Pampo-Malhado'],
  'Trachinotus spp.': ['Pampo', 'Canguira'],
  'Trachurus picturatus': ['Chicharro', 'Xixarro', 'Surel', 'Carapau-Negro'],
  'Trachurus spp.': ['Chicharro', 'Xixarro'],
  'Trachurus symmetricus': ['Chicharro', 'Xixarro', 'Carapau-do-Pacífico'],
  'Trachurus trachurus': ['Chicharro', 'Xixarro', 'Guaraçuma'],
  'Trichiurus lepturus': ['Peixe-Espada'],
  'Triportheus spp.': ['Sardinha-Comprida', 'Sardinha-Papuda'],
  'Tylosurus acus': ['Agulhão'],
  'Umbrina spp.': ['Castanha', 'Chora-Chora'],
  'Urophycis spp.': ['Abrótea'],
  'Xiphias gladius': ['Espadarte', 'Meka', 'Meca'],
  'Zapteryx brevirostris': ['Viola', 'Cação-Viola', 'Banjo'],
  'Zenopsis conchifer': ['Peixe-Galo-Branco'],
  'Zeus faber': ['Peixe-Galo-Negro'],
  'Zungaro jahu': ['Jaú'],
  'Zungaro zungaro': ['Jaú PEIXES HÍBRIDOS DE INTERESSE COMERCIAL NOME CIENTÍFICO NOME COMUM Colossoma macropomum x'],
};

/// Índice inverso, montado uma vez: nome comum sem acento -> científicos.
Map<String, List<String>>? _porComum;

Map<String, List<String>> get _indice {
  if (_porComum != null) return _porComum!;
  final m = <String, List<String>>{};
  nomesOficiais.forEach((cient, comuns) {
    for (final c in comuns) {
      final chave = semAcentoNome(c);
      final d = m.putIfAbsent(chave, () => <String>[]);
      if (!d.contains(cient)) d.add(cient);
    }
  });
  _porComum = m;
  return m;
}

/// Tira acento e caixa, para comparar o que a pessoa digitou.
String semAcentoNome(String s) {
  const de = 'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ';
  const para = 'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC';
  final b = StringBuffer();
  for (final ch in s.split('')) {
    final i = de.indexOf(ch);
    b.write(i >= 0 ? para[i] : ch);
  }
  return b.toString().toLowerCase().trim();
}

/// Os nomes comuns oficiais de um nome científico.
///
/// Aceita a grafia com sinônimo separado por barra ("Mugil platanus /
/// Mugil liza") e a que traz um terceiro termo, tentando o gênero mais
/// o epíteto quando o nome inteiro não casa.
List<String> comunsDe(String cientifico) {
  for (final parte in cientifico.split('/')) {
    final p = parte.trim();
    if (p.isEmpty) continue;
    final direto = nomesOficiais[p];
    if (direto != null) return direto;
    final t = p.split(RegExp(r'\s+'));
    if (t.length >= 2) {
      final dois = nomesOficiais['${t[0]} ${t[1]}'];
      if (dois != null) return dois;
    }
  }
  return const [];
}

/// Os nomes científicos que atendem por um nome comum.
///
/// Busca por começo de palavra: "carap" devolve carapeba e carapau.
List<String> cientificosDe(String nomeComum) {
  final termo = semAcentoNome(nomeComum);
  if (termo.length < 3) return const [];
  final saida = <String>[];
  _indice.forEach((comum, cients) {
    if (comum.startsWith(termo) || comum.contains('-$termo') ||
        comum.contains(' $termo')) {
      for (final c in cients) {
        if (!saida.contains(c)) saida.add(c);
      }
    }
  });
  saida.sort();
  return saida;
}

/// Como mostrar na tela: "Carapeba" ou "Corvina, Curuca, Cascote".
String comunsEmLinha(String cientifico) => comunsDe(cientifico).join(', ');

int get quantasEspeciesNomeadas => nomesOficiais.length;
